import http from 'node:http';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve,extname,sep} from 'node:path';
import {randomUUID,randomInt} from 'node:crypto';
import {createMatch,command,botCommand,viewFor} from './packages/engine/index.mjs';
import {chapters,defaultDeck,enemyDeck,cardById} from './packages/content/cards.mjs';
const root=resolve('.'),publicRoot=resolve('public'),dataDir=resolve(process.env.DATA_DIR||'data'),profilesFile=resolve(dataDir,'profiles.json');
await mkdir(dataDir,{recursive:true});let profiles={};try{profiles=JSON.parse(await readFile(profilesFile,'utf8'));}catch(e){if(e.code!=='ENOENT')throw e;}
let saveQueue=Promise.resolve();function save(){const snapshot=JSON.stringify(profiles,null,2);saveQueue=saveQueue.then(()=>writeFile(profilesFile,snapshot));return saveQueue;}
const matches=new Map(),rooms=new Map(),streams=new Map();
const cleanProfile=p=>({id:p.id,name:p.name,progress:p.progress,rating:p.rating,wins:p.wins,storyWins:p.storyWins,deck:p.deck});
const reply=(res,data,status=200)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));};
function notify(match){for(let actor=0;actor<match.ids.length;actor++){const id=match.ids[actor];for(const res of streams.get(id)||[])res.write(`data: ${JSON.stringify({matchId:match.id,actor,state:viewFor(match.state,actor),names:match.names,kind:match.kind,chapter:match.chapter,profile:cleanProfile(profiles[id])})}\n\n`);}}
async function finish(match){if(match.state.winner===null||match.recorded)return;match.recorded=true;if(match.kind==='story'&&match.state.winner===0){const p=profiles[match.ids[0]];p.progress=Math.max(p.progress,match.chapter+1);p.storyWins++;}if(match.kind==='online'&&match.state.winner!=='draw'){const w=profiles[match.ids[match.state.winner]],l=profiles[match.ids[1-match.state.winner]];const delta=Math.round(24*(1-1/(1+10**((l.rating-w.rating)/400))));w.rating+=delta;l.rating=Math.max(0,l.rating-delta);w.wins++;}await save();}
function runBot(match){if(match.kind!=='story'||match.state.active!==1||match.state.winner!==null)return;setTimeout(async()=>{if(match.state.active!==1||match.state.winner!==null)return;try{match.state=command(match.state,1,botCommand(match.state));await finish(match);notify(match);runBot(match);}catch(e){console.error('Bot error:',e.message);}},Number(process.env.BOT_DELAY_MS||650));}
function current(id){return [...matches.values()].reverse().find(m=>m.ids.includes(id)&&m.state.winner===null);}
async function body(req){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>16384)throw Error('İstek çok büyük.');}return raw?JSON.parse(raw):{};}
const server=http.createServer(async(req,res)=>{
 try{
  const url=new URL(req.url,'http://localhost');
  if(url.pathname.startsWith('/api/')){
   if(url.pathname==='/api/session'&&req.method==='POST'){const b=await body(req);let p=Object.values(profiles).find(p=>p.token===b.token);if(!p){const id=randomUUID();p={id,token:randomUUID(),name:'Gezgin '+Object.keys(profiles).length,progress:0,rating:1000,wins:0,storyWins:0,deck:[...defaultDeck]};profiles[id]=p;await save();}return reply(res,{token:p.token,profile:cleanProfile(p)});}
   const token=req.headers.authorization?.replace('Bearer ','')||url.searchParams.get('token');const p=Object.values(profiles).find(p=>p.token===token);if(!p)return reply(res,{error:'Oturum bulunamadı.'},401);
   if(url.pathname==='/api/events'){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive'});res.write(': connected\n\n');if(!streams.has(p.id))streams.set(p.id,new Set());streams.get(p.id).add(res);const m=current(p.id);if(m)notify(m);const timer=setInterval(()=>res.write(': ping\n\n'),20000);req.on('close',()=>{clearInterval(timer);streams.get(p.id)?.delete(res);});return;}
   if(url.pathname==='/api/profile'&&req.method==='GET')return reply(res,cleanProfile(p));
   if(url.pathname==='/api/profile'&&req.method==='POST'){const b=await body(req);if(b.name!==undefined){const name=String(b.name).trim();if(!name||name.length>24)throw Error('Ad 1–24 karakter olmalı.');p.name=name;}if(b.deck){if(!Array.isArray(b.deck)||b.deck.length!==20||b.deck.some(c=>!cardById[c])||b.deck.some(id=>b.deck.filter(c=>c===id).length>3))throw Error('Deste 20 kart içermeli; bir kart en fazla 3 kez kullanılabilir.');p.deck=b.deck;}await save();return reply(res,cleanProfile(p));}
   if(url.pathname==='/api/leaderboard'){const list=Object.values(profiles).sort((a,b)=>b.progress-a.progress||b.rating-a.rating||b.wins-a.wins);return reply(res,list.map((x,i)=>({...cleanProfile(x),rank:i+1,deck:undefined})));}
   if(url.pathname==='/api/match'&&req.method==='GET'){const m=current(p.id);return reply(res,m?{matchId:m.id,actor:m.ids.indexOf(p.id),state:viewFor(m.state,m.ids.indexOf(p.id)),names:m.names,kind:m.kind,chapter:m.chapter}:null);}
   if(url.pathname==='/api/story'&&req.method==='POST'){const b=await body(req);const ch=chapters[b.chapter];if(!ch||ch.id>p.progress)throw Error('Bu bölüm henüz açılmadı.');if(current(p.id))throw Error('Önce devam eden maçını tamamla.');if(!['ash','white','teom'].includes(b.echo))throw Error('Geçersiz Yankı.');const id=randomUUID();const m={id,ids:[p.id],names:[p.name,ch.opponent],kind:'story',chapter:ch.id,state:createMatch({seed:ch.seed,echo:[b.echo,ch.id===4?'white':'ash'],health:[24,ch.health],decks:[p.deck,ch.id===4?defaultDeck:enemyDeck]})};matches.set(id,m);notify(m);return reply(res,{matchId:id,actor:0,state:viewFor(m.state,0),names:m.names,kind:m.kind,chapter:m.chapter});}
   if(url.pathname==='/api/room'&&req.method==='POST'){if(current(p.id))throw Error('Önce devam eden maçını tamamla.');const b=await body(req);if(b.echo&&!['ash','white','teom'].includes(b.echo))throw Error('Geçersiz Yankı.');if(b.action==='cancel'){for(const [code,r]of rooms)if(r.host===p.id)rooms.delete(code);return reply(res,{cancelled:true});}if(b.action==='create'){for(const [code,r]of rooms)if(r.host===p.id)rooms.delete(code);let code;do{code=String(randomInt(100000,999999));}while(rooms.has(code));rooms.set(code,{host:p.id,progress:p.progress,echo:b.echo||'ash',created:Date.now()});return reply(res,{code,progress:p.progress});}const code=String(b.code),room=rooms.get(code);if(!room||Date.now()-room.created>1800000)throw Error('Oda bulunamadı veya süresi doldu.');if(room.host===p.id)throw Error('Odaya başka bir tarayıcı oturumundan katıl.');if(current(room.host)){rooms.delete(code);throw Error('Oda sahibi başka bir maçta.');}if(p.progress!==profiles[room.host].progress)throw Error('Rakibinle aynı hikâye katmanında olmalısın.');const host=profiles[room.host];const id=randomUUID();const m={id,ids:[host.id,p.id],names:[host.name,p.name],kind:'online',state:createMatch({seed:randomInt(1,10000000),first:randomInt(0,2),echo:[room.echo,b.echo||'ash'],decks:[host.deck,p.deck]})};matches.set(id,m);rooms.delete(code);notify(m);return reply(res,{matchId:id,actor:1,state:viewFor(m.state,1),names:m.names,kind:m.kind});}
   if(url.pathname==='/api/command'&&req.method==='POST'){const b=await body(req);const m=matches.get(b.matchId);if(!m||!m.ids.includes(p.id))throw Error('Maç bulunamadı.');m.state=command(m.state,m.ids.indexOf(p.id),b.command);await finish(m);notify(m);runBot(m);return reply(res,{state:viewFor(m.state,m.ids.indexOf(p.id)),profile:cleanProfile(p)});}
   return reply(res,{error:'Uç nokta bulunamadı.'},404);
  }
  if(!['GET','HEAD'].includes(req.method)){res.writeHead(405);res.end();return;}
  let file;if(url.pathname.startsWith('/packages/')){file=resolve(root,'.'+decodeURIComponent(url.pathname));if(!file.startsWith(resolve(root,'packages')+sep))throw Error('Geçersiz yol.');}else{file=resolve(publicRoot,'.'+decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname));if(!file.startsWith(publicRoot+sep))throw Error('Geçersiz yol.');}
const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.js':'text/javascript; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp','.woff2':'font/woff2','.ttf':'font/ttf','.svg':'image/svg+xml'};const bytes=await readFile(file);res.writeHead(200,{'Content-Type':types[extname(file)]||'application/octet-stream','X-Content-Type-Options':'nosniff'});res.end(req.method==='HEAD'?undefined:bytes);
 }catch(e){if(e.code==='ENOENT')return reply(res,{error:'Dosya bulunamadı.'},404);return reply(res,{error:e.message},400);}
});
const port=Number(process.env.PORT||3000);server.listen(port,'0.0.0.0',()=>console.log(`ERULDIN: YANKILAR → http://localhost:${port}`));
