import test from 'node:test';
import assert from 'node:assert/strict';
import {createMatch,command,botCommand,viewFor} from '../packages/engine/index.mjs';
import {cards,cardById} from '../packages/content/cards.mjs';
function fixture(){const s=createMatch({seed:42});s.players.forEach(p=>{p.board=[];p.energy=10;p.maxEnergy=10;p.hand=[];p.hp=14;});return s;}
function hand(s,id){const h={id,uid:s.nextId++};s.players[0].hand=[h];return h.uid;}
function unit(s,actor,id='karah',hp=3,attack=3){const u={id,uid:s.nextId++,hp,attack};s.players[actor].board.push(u);return u;}
test('Same seed and commands produce an identical complete replay',()=>{let a=createMatch({seed:123}),b=createMatch({seed:123});for(let i=0;i<300&&a.winner===null;i++){const cmd=botCommand(a),actor=a.active;a=command(a,actor,cmd);b=command(b,actor,cmd);}assert.deepEqual(a,b);assert.notEqual(a.winner,null);});
test('Commands and bot decisions never mutate input state',()=>{let s=createMatch();const snapshot=structuredClone(s),decision=botCommand(s);assert.deepEqual(s,snapshot);command(s,s.active,decision);assert.deepEqual(s,snapshot);});
test('Opponent hand and both deck orders stay private',()=>{const s=createMatch(),v=viewFor(s,0);assert.equal(v.players[1].hand.length,5);assert.ok(v.players[1].hand.every(h=>h.hidden&&h.id===undefined));assert.equal(v.players[0].deck,undefined);assert.equal(v.players[1].deck,undefined);assert.equal(v.commands,undefined);assert.equal(v.players[0].hand.length,5);});
test('Out of turn play and invalid card ownership are rejected',()=>{const s=createMatch();assert.throws(()=>command(s,1,{type:'pass'}));assert.throws(()=>command(s,0,{type:'play',uid:999}));assert.throws(()=>command(s,2,{type:'pass'}));});
test('Insufficient Essence and a full line reject without consuming card',()=>{const s=fixture(),uid=hand(s,'teom');s.players[0].energy=0;assert.throws(()=>command(s,0,{type:'play',uid}));s.players[0].energy=10;for(let i=0;i<5;i++)unit(s,0);assert.throws(()=>command(s,0,{type:'play',uid}));assert.equal(s.players[0].hand[0].uid,uid);});
for(const c of cards)test(`Card effect: ${c.id}`,()=>{const s=fixture();const uid=hand(s,c.id);const enemy=unit(s,1,'karah',6,2),ally=unit(s,0,'karah',3,2);const deckSize=s.players[0].deck.length;const result=command(s,0,{type:'play',uid,...(c.target?{target:enemy.uid}:{})});const p=result.players[0],o=result.players[1];assert.equal(p.energy,10-c.cost);assert.ok(p.memory>=1);if(c.type!=='spell')assert.ok(p.board.some(u=>u.id===c.id));switch(c.effect){case'memory':assert.equal(p.memory,2);break;case'recall':assert.equal(p.deck.length,deckSize-1);assert.equal(p.memory,2);break;case'restore':assert.equal(p.hp,16);break;case'damage':assert.equal(o.board[0].hp,3);break;case'draw':assert.equal(p.hand.length,2);assert.equal(p.memory,2);break;case'heal':assert.equal(p.hp,19);break;case'aoe':assert.equal(o.board[0].hp,4);break;case'buff':assert.equal(p.board.find(x=>x.uid===ally.uid).attack,3);assert.equal(p.board.find(x=>x.uid===ally.uid).hp,5);break;}assert.equal(result.active,c.keyword==='anlik'?0:1);});
test('Shelter forces targeted spells onto guards',()=>{let s=fixture();const uid=hand(s,'blade'),guard=unit(s,1,'akhenten',7,3),other=unit(s,1,'karah',2,3);assert.throws(()=>command(s,0,{type:'play',uid,target:'avatar'}));assert.throws(()=>command(s,0,{type:'play',uid,target:other.uid}));s=command(s,0,{type:'play',uid,target:guard.uid});assert.equal(s.players[1].board[0].hp,4);});
test('Double pass advances the round, draws and transfers assault',()=>{let s=createMatch();s=command(s,0,{type:'pass'});assert.equal(s.round,1);s=command(s,1,{type:'pass'});assert.equal(s.round,2);assert.equal(s.active,1);assert.equal(s.attackOwner,1);assert.equal(s.players[0].energy,3);assert.equal(s.players[0].hand.length,6);});
test('A blocker absorbs the attack and both units take damage simultaneously',()=>{let s=fixture();const a=unit(s,0,'karah',4,3),b=unit(s,1,'karah',4,2);s=command(s,0,{type:'attack',units:[a.uid]});assert.equal(s.phase,'block');s=command(s,1,{type:'block',pairs:{[a.uid]:b.uid}});assert.equal(s.players[0].board[0].hp,2);assert.equal(s.players[1].board[0].hp,1);assert.equal(s.players[1].hp,14);assert.equal(s.active,1);assert.equal(s.phase,'main');});
test('Unblocked attackers hit the avatar; an assault can occur only once per round',()=>{let s=fixture();const a=unit(s,0,'karah',2,3);s=command(s,0,{type:'attack',units:[a.uid]});s=command(s,1,{type:'block'});assert.equal(s.players[1].hp,11);s=command(s,1,{type:'pass'});assert.throws(()=>command(s,0,{type:'attack',units:[a.uid]}));});
test('One unit cannot block multiple attackers and a foreign blocker is rejected',()=>{let s=fixture();const a=unit(s,0),b=unit(s,0),blocker=unit(s,1);s=command(s,0,{type:'attack',units:[a.uid,b.uid]});assert.throws(()=>command(s,1,{type:'block',pairs:{[a.uid]:blocker.uid,[b.uid]:blocker.uid}}));assert.throws(()=>command(s,1,{type:'block',pairs:{[a.uid]:a.uid}}));});
test('Trace kills before retaliation; Marcel grows after combat',()=>{let s=fixture();const a=unit(s,0,'onbion',3,5),b=unit(s,1,'karah',2,3);s=command(s,0,{type:'attack',units:[a.uid]});s=command(s,1,{type:'block',pairs:{[a.uid]:b.uid}});assert.equal(s.players[0].board[0].hp,3);assert.equal(s.players[1].board.length,0);s=fixture();const m=unit(s,0,'marcel',4,3);s=command(s,0,{type:'attack',units:[m.uid]});s=command(s,1,{type:'block'});assert.equal(s.players[0].board[0].attack,4);});
for(const echo of ['ash','white','teom'])test(`Echo power: ${echo} is charged and once per match`,()=>{let s=fixture();s.players[0].echo=echo;s.players[0].memory=5;s.players[0].energy=2;assert.throws(()=>command(s,0,{type:'ultimate'}));s.players[0].memory=6;unit(s,0);unit(s,1,'karah',2);s=command(s,0,{type:'ultimate'});assert.equal(s.players[0].ultimateUsed,true);assert.equal(s.players[0].memory,0);if(echo==='ash'){assert.equal(s.players[0].board[0].attack,5);assert.equal(s.players[0].hp,17);}if(echo==='white'){assert.equal(s.players[0].hand.length,1);assert.equal(s.players[0].hp,20);assert.equal(s.players[0].energy,5);}if(echo==='teom')assert.equal(s.players[1].board.length,0);s.active=0;s.players[0].memory=6;assert.throws(()=>command(s,0,{type:'ultimate'}));});
test('Fatigue increases when deck is empty and healing respects maximum',()=>{let s=fixture();s.players[0].deck=[];const uid=hand(s,'memory');s=command(s,0,{type:'play',uid});assert.equal(s.players[0].hp,11);assert.equal(s.players[0].fatigue,2);s=fixture();s.players[0].hp=23;const fire=hand(s,'fire');s=command(s,0,{type:'play',uid:fire});assert.equal(s.players[0].hp,24);});
test('Concession works outside priority; finished matches reject additional commands',()=>{const s=createMatch();const result=command(s,1,{type:'concede'});assert.equal(result.winner,0);assert.throws(()=>command(result,0,{type:'pass'}));});
test('Initial Echo passives and hand limits',()=>{const s=createMatch({echo:['white','teom']});assert.equal(s.players[0].memory,1);assert.equal(s.players[1].maxHp,25);let f=fixture();f.players[0].hand=Array.from({length:9},(_,i)=>({id:'memory',uid:200+i}));f=command(f,0,{type:'play',uid:200});assert.equal(f.players[0].hand.length,9);});
