from pathlib import Path
import json,re,hashlib,shutil,csv,struct
ROOT=Path.cwd(); PACK=ROOT/'design-pack'; MAP=PACK/'12-campaign-map'; EN=PACK/'13-enemies'; STORY=PACK/'14-campaign'
SOURCE=Path('C:/Users/PC/Desktop/Eruldin Destanı haritası sitesi')
for p in [MAP/'source-world',MAP/'data',MAP/'models',EN/'art',STORY]:p.mkdir(parents=True,exist_ok=True)
def dump(path,data):path.write_text(json.dumps(data,ensure_ascii=False,indent=2),encoding='utf-8')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
selected=['public/assets/terrain/world.webp','public/assets/terrain/surface.bin','public/assets/terrain/northwest.webp','public/assets/terrain/northeast.webp','public/assets/terrain/southwest.webp','public/assets/terrain/southeast.webp','public/assets/terrain-cinematic-v4.png','public/assets/heightmap.png','public/assets/materials/forest-earth.png']
selected += [f'public/assets/terrain-detail/{n}.png' for n in ['northwest','northeast','southwest','southeast']]
copies=[]
for rel in selected:
 src=SOURCE/rel
 if not src.exists():continue
 dest=MAP/'source-world'/Path(rel).relative_to('public/assets');dest.parent.mkdir(parents=True,exist_ok=True);h=sha(src);shutil.copy2(src,dest)
 copies.append({'source':str(src),'asset':dest.relative_to(PACK).as_posix(),'bytes':src.stat().st_size,'sha256_source':h,'sha256_copy':sha(dest),'source_mtime_ns':src.stat().st_mtime_ns})
sourcefiles=['src/data/world.ts','src/data/regions.ts','src/data/lore.ts','src/data/regionalLife.ts','src/data/terrainSurface.ts','src/data/cartography.ts']
dump(MAP/'data/source-preservation.json',{'policy':'Kaynak klasöre yazılmadı; yalnızca sanat ve veriler ayrı pakete kopyalandı.','copies':copies,'read_only_source_records':[{'path':str(SOURCE/s),'sha256':sha(SOURCE/s),'mtime_ns':(SOURCE/s).stat().st_mtime_ns} for s in sourcefiles if (SOURCE/s).exists()]})
atlas=json.loads((MAP/'data/atlas-original.json').read_text(encoding='utf-8'))
book=ROOT/'docs/source-text/Marcel 1. kitap v14.txt';parts=re.split(r'--- PDF SAYFA (\d+) ---',book.read_text(encoding='utf-8'));pages={int(parts[i]):parts[i+1] for i in range(1,len(parts),2)}
entities=['Korvengrad','Koru','Kül Tarlaları','Kırık Diş','Manastır','Kuzgunyuvası','Ölüler Bataklığı','Kızıl Kale','Akhenten','Onbion','Borin','Torg','Gorn','Valerus','Fiona','Primus','Tensar','Anzer','Vesemir','Shiro','Karah','Teom']
dump(STORY/'book-page-index.json',{'source':book.name,'pages':len(pages),'method':'100 sayfanın metni indekslendi; konum, karakter ve rota kayıtları PDF sayfasıyla ilişkilendirildi. Bu indeks satır satır editoryal okuma iddiası değildir.','page_records':[{'page':n,'sha256':hashlib.sha256(t.encode()).hexdigest(),'characters':len(t),'entities':[e for e in entities if e.casefold() in t.casefold()]} for n,t in pages.items()]})
families=[
 ('karah-crawler','Karah / Sürü','karah','Korvengrad;Serath', [3,4,5,6,72], 'Zift siyahı / kemik beyazı','Aynı turda üçüncü Karah oynanınca bir 1/1 Zift Larvası yarat.','Zift Larvası|Duvar Sürüneni|Katedral Tırmanıcısı|Çatlak Çene|Kör Pençe|Kambur Takipçi|Tavan Avcısı|Çokbacak|Koku Arayıcısı|Kemik Taşıyıcı|Sürü Öncüsü|Karah Anaç','Zift İzi|Kara Sıçrama|Duvar Pususu|Parçalı Hücum|Yırtık Eklemler|Boğucu Koku|Pençe Yağmuru|Çatlakta Saklan|Sürü Çağrısı|Kemik Isırığı|Zift Perdesi|Karanlık Açlığı'),
 ('karah-armored','Karah / Zırhlı','karah','Korvengrad;Shi Qra',[5,6,72],'Mat obsidyen / kirli gümüş','Turun ilk Karahı 1 Zırh kazanır; Zırh ilk hasarı 1 azaltır.','Karah Kabuklu|Plaka Kıran|Demir Omurga|Kırık Miğfer|Zift Omuz|Kule Yıkan|Çelik Çene|Kabuk Muhafızı|Ağır Pençe|Omurga Yığını|Kara Koç|Hisar Deviren','Kabuk Sertleşmesi|Omurga Örtüsü|Demir Çatlağı|Plaka Darbesi|Ağır Adım|Zift Zırhı|Baskı Dalgası|Kemik Kalkan|Savrulan Enkaz|Omuz Hücumu|Karanlık Direnç|Son Kabuğun Kırılışı'),
 ('karah-stalker','Karah / Pusu','karah','Kül Tarlaları;Aldemir',[4,6,19,72],'Kurum / soğuk mor','İlk saldırı hazırlığında en zayıf düşmanı İşaretle; işaretli hedefe bu tur ilk vuruş +1.','Gölge Karah|Sessiz Eklem|Kül Koklayan|Yarık Sürüneni|Gece Pençesi|Sırt Takipçisi|Kör Göz|Bozuk Siluet|Karanlık Kanca|Sinsi Diş|Zift Gözcüsü|Pusu Biçeni','Kokuya Kilitlen|Sessiz Sıçrayış|Arka Sokak|Zift Tuzağı|Karanlığa Çekil|Gölge Çentiği|Boş Bakış|Gece Yarası|Kül Perdesi|Ani Pençe|İz Yitimi|Son Takip'),
 ('korvengrad-watch','Korvengrad Muhafızları','human','Korvengrad;Teomli',[1,8,10],'Gri taş / soluk pirinç','Savunan ilk muhafız +1 Can kazanır; kent savunma rolü oyun eklemesidir.','Sokak Nöbetçisi|Mızrakçı|Katedral Bekçisi|Kapı Kalkanı|Çatı Okçusu|Fener Taşıyıcı|Nöbet Onbaşısı|Kule Gözcüsü|Zincir Muhafızı|Siper Ustası|Devriye Çavuşu|Kent Komutanı','Nöbet Değişimi|Kapıyı Tut|Dar Sokak|Kalkan Birliği|Alarm Çanı|Çatı Atışı|Fener İşareti|Demir Barikat|Gece Devriyesi|Siper Emri|Mızrak Duvarı|Son Savunma'),
 ('korvengrad-corrupt','Korvengrad Yozlaşmış Birliği','human-corrupt','Korvengrad;Serath',[8,10,71],'Pas / koyu bordo','İlk hasar alan müttefik 1 Yozlaşma alır; üç Yozlaşmada +2 Saldırı fakat tur sonunda 1 Can kaybı.','Paslı Nöbetçi|Çatlak Vizör|Kayıp Devriye|Kül Lejyoneri|Mühürlü Asker|Kara Damar|İnfaz Yazıcısı|Yozlaşmış Okçu|Kör Teğmen|Boş Miğfer|Katedral Celladı|Paslı Komutan','Çürük Yemin|Paslı Düzen|Kara Emir|Boş Nöbet|Damar Zehri|Çan Susuşu|İnfaz Hattı|Mühür Baskısı|Kayıp Talimat|Kül Disiplini|Çatlak Siper|Son Emir'),
 ('koru-jail','Koru / Zindan Birliği','krov-human','Koru;Shi Qra',[30,31,32,35,36],'Demir / mantar kehribarı','Her ikinci savunmada 1 Zincir biriktir; üç Zincirle bir düşmanı bir tur saldırıdan alıkoy.','Zindan Nöbetçisi|Anahtar Taşıyıcı|Zincirci|Hücre Bekçisi|Tünel Gözcüsü|Maden Muhafızı|Kapı Krov’u|Sürgü Ustası|Mahzen Okçusu|Demir Eldiven|Zindan Çavuşu|Hücre Kumandanı','Sürgü Çek|Paslı Zincir|Mazgal|Anahtar Nöbeti|Dar Hücre|Demir Kilit|Sessizlik Emri|Karanlık Kapı|Nöbet Alarmı|Mahzen Pususu|Zincir Darbesi|Kaçışın Kesilişi'),
 ('koru-forge','Koru / Demirhane Birliği','krov-human','Koru;Shi Qra',[26,29,60,61,62],'Koyu çelik / köz turuncusu','Maliyet 4+ müttefik oynandığında 1 Isı; üç Isı harcayıp birime +1/+1 ver.','Ocak Muhafızı|Körükçü Asker|Demir Mızrak|Cüruf Kalkanı|Dövme Zırhlı|Çekiç Taşıyıcı|Kömür Okçusu|Pota Bekçisi|Su Varili Gözcüsü|Ocak Çavuşu|Zırh Ustası|Demirhane Kumandanı','Körüğü Aç|Pota Kızgınlığı|Cüruf Yağmuru|Tavlı Çelik|Su Buharı|Ocak Siperi|Kızıl Dövme|Yedek Plaka|Demir Parçası|Isı Baskısı|Örs Darbesi|Son Tavlama'),
 ('valerus-loyal','Valerus’un Sadık Birliği','human-krov','Koru;Teomli',[25,30,32,64,65],'Parlak çelik / siyah kırmızı','Emir kartı oynandıktan sonraki ilk asker +1 Saldırı; yalnızca Valerus’a bağlı birlik düşmandır.','Sadık Kalkan|Doğu Mızrakçısı|Ziyafet Nöbetçisi|Liderin Okçusu|Salon Muhafızı|Söz Taşıyıcı|Direniş Onbaşısı|Gizli Teslimatçı|Kapalı Vizör|Kumandan Yaveri|Yeminli Asker|Bölük Reisi','Sadakat Emri|Sözde Barış|Teslimat Listesi|Salon Kuşatması|Liderin Sözü|Kalkan Disiplini|Ziyafet Tuzağı|Gizli Geçit|Yemin Baskısı|Komuta Zinciri|Kırık Güven|Son Buyruk'),
 ('council','Konsey / Gölge Yolu','inhuman-human','Kızıl Kale;Val Teresh',[63,64,65,66,83,91],'Siyah / koyu şarap','İlk kontrol büyüsünde 1 Mühür; üç Mühürle düşman birimini bir tur sürgüne çıkar.','Mühür Taşıyıcı|Gölge Kâtibi|Siyah Asa|Elçinin Gözcüsü|Kapı Yazıcısı|Konsey Hizmetlisi|Duman Habercisi|Karanlık Arabulucu|Mühür Okuyucusu|İrade Gözcüsü|Gölge Elçisi|Buyruk Nazırı','Gölge Yolu|Siyah Küre|Zorunlu Davet|Mühür Fısıltısı|Kara Geçit|Elçinin Hükmü|Gölge Kaydı|İrade Baskısı|Susturma|Eksik Cevap|Konsey Çağrısı|Son Mühür'),
 ('butterfly-guard','Kızıl Kale / Kelebek Muhafızları','human','Kızıl Kale;Val Teresh',[88,89,94,99],'Koyu kızıl / siyah metal','Her turun ilk Siper birimi Kelebek İşareti alır: komşu müttefiki ilk 1 hasardan korur.','Ağızsız Maske|Koridor Muhafızı|Kelebek Nöbetçisi|Siyah Metal Kalkan|Merdiven Gardiyanı|Asalı Gözcü|Taç Maskesi|Hücre Anahtarcısı|Kızıl Salon Askeri|İç Kapı Bekçisi|Naibenin Muhafızı|Kale Kumandanı','Kelebek İşareti|Koridor Disiplini|Zinciri Çöz|Taş Kapı|Siyah Zemin|Sessiz Emir|Kızıl Çizgi|Maskenin Ardında|Misafir Protokolü|Kapalı Yol|Kale Nöbeti|Son Koridor'),
 ('living-fortress','Kızıl Kale / Canlı Taş','construct','Kızıl Kale;Val Teresh',[86,88,91,94,100],'Kan taşı / siyah damar','Her üçüncü tur 0/3 Duvar Damarı yarat; damar varken ilk büyüye 1 geçici enerji.','Duvar Damarı|Taş Kulak|Kızıl Yarık|Zincir Kancası|Metal Dalga|Koridor Ağzı|Kafatası Nişi|Canlı Eşik|Siyah Taht İzi|Dinleyen Taş|Kızıl Kemer|Kalenin Kalbi','Taşlar Dinliyor|Duvarı Aç|Kan Hafızası|Yaşayan Zincir|Kızıl Nefes|Labirent|Damar Titreşimi|Kapısız Salon|Taş Kapanı|Siyah Dalga|Kayıt Tutan Duvar|Son Eşik'),
 ('ash-scavenger','Kül Tarlaları / Yağmacılar','human','Kül Tarlaları;Serath',[14,19,73,74,75],'Kül beji / eski bakır','İlk yok olan müttefik 1 Hurda verir; iki Hurda harcayarak bir kartın maliyetini 1 düşür.','Kül Toplayıcı|Su Kesici|Hurda Okçusu|Boru Saklananı|Erzak Avcısı|Paslı Bıçak|Toz Maskesi|Kervan Pusucusu|Enkaz Gözcüsü|Gümüş Kesici|Yağma Reisi|Tarlanın Zorbası','Suya El Koy|Hurda Bağı|Kül Pususu|Erzak Payı|Toz Bulutu|Boru Siperi|Paslı Tuzak|Kervan Kes|Son Damla|Kayıp Çanta|Enkaz Yağması|Son Pazarlık'),
 ('marsh-visions','Ölüler Bataklığı / Sanrılar','vision','Ölüler Bataklığı;Aldemir',[82,84],'Solgun yeşil / çamur','İlk kaybedilen birim 1 Sis bırakır; üç Sisle oyuncu saldırı önizlemesi bulanıklaşır ama gerçek değerler incelemede görünür.','Gaz Silueti|Boş Yüz|Kayıp Asker Yankısı|Çamur Eli|Korku Gölgesi|Bataklık Nefesi|Durgun Su Sureti|Yas Yansıması|Sis Çığlığı|Çürük Bayrak|Ölü Nöbet|Sanrı Düğümü','Gaz Soluğu|Yanlış Hatıra|Derin Korku|Çamur Çekişi|Sis Kapanı|Bozuk Yansıma|Yol Kaybı|Durgun Fısıltı|Savaş Artığı|Korkuya Bak|Nefes Kes|Son Sanrı'),
 ('pass-raiders','Geçit / Akıncılar','human','Kırık Diş Geçidi;Serath',[20,21,28,32,82],'Koyu deri / kaya grisi','Savunmasız düşmana ilk saldırı sonrası bir akıncı geri çekilip bir kart çektirir.','Geçit Gözcüsü|Kayalık Okçu|İp Kesici|Kaya Pusucusu|Dar Yol Bıçağı|Halat Akıncısı|Çıkıntı Mızrağı|Taş Yağmacısı|Kervan İzleyici|Uçurum Reisi|Kırık Diş Avcısı|Geçit Zorbası','Halatı Kes|Kaya Düşüşü|Dar Patika|Yükü Bırak|Uçurum Pususu|Geçidi Tut|Geri Çekil|Kaya Siperi|İp Tuzağı|Kervan Ablukası|Yan Geçit|Son Çıkıntı'),
 ('shi-qra-outlaws','Shi Qra / Kaçak Savaşçılar','krov','Shi Qra',[32,39],'Demir / kızıl keçe','Tek başına saldıran ilk Krov +2 Saldırı kazanır; yardım isteyince bonus biter.','Demir İzci|Bozkır Kaçağı|Ocak Serserisi|Taş Kalkan|Keçe Pusucu|Çekiç Akıncı|Yamaç Gözcüsü|Kızıl Sırt Binicisi|Demirkanat Terbiyecisi|Göç Yolu Kesici|Kaçak Reis|Dağ Düellocusu','Yuvarlanan Taş|Göç İzi|Demir Yemin|Yalnız Düello|Rüzgâr Siperi|Ocak Yolu|Bozkır Pususu|Keçe Kalkan|Dar Vadi|Demir Sınav|Kaçak Çağrısı|Son Düello'),
 ('forest-predators','Aldemir / Orman Avcıları','beast','Aldemir',[],'Yosun / safir yeşil','Yaralı düşmanı vuran ilk yaratık 1 Can iyileşir.','Kök Pençesi|Göl Dişi|Orman Pusucusu|Reçine Sırtı|Karanlık Vahna|Yaprak Avcısı|Diken Sürüneni|Çalı Göz|Safir Pusu|Gürz Gölgesi|Av Sürüsü|Orman Baskını','Kök Kapanı|Reçine İzi|Av Kokusu|Göl Siperi|Diken Çemberi|Çalıya Sin|Yaprak Perdesi|Safir Yansıma|Karanlık Orman|Sürü Takibi|Yaraya Kilitlen|Son Av'),
 ('desert-hunters','Zağra Khur / Kum Avcıları','beast','Zağra Khur',[],'Kum altını / obsidyen','İlk saldırmayan yaratık Gömülü olur: sonraki tur ilk vuruş +2; görünür işaret korunur.','Kum Pençesi|Kuyu Avcısı|Cam Kabuk|Titreşim İzci|Karathaxi Yavrusu|Vaha Pususu|Kum Çenesi|Taş Sığınanı|Gömülü Omurga|Cam Kuyruk|Karathaxi Öncüsü|Kumun Yutucusu','Kum Altında|Titreşim Takibi|Kuyu Kapanı|Cam Kırığı|Vaha Ablukası|Sıcak Rüzgâr|Gömülü Tuzak|Kum Perdesi|Susuz İz|Taşa Çık|Vaha Kokusu|Son Titreşim'),
 ('frost-predators','Ebedi Buzullar / Aç Yırtıcılar','beast','Ebedi Buzullar',[],'Buz mavisi / kirli beyaz','Her ikinci yaralama bir Soğuk verir; üç Soğuk hedefin sonraki saldırısını 1 azaltır.','Kar Vahnası|Buz Koklayan|Aç Vesuni|Kırağı Pençesi|Kar İzcisi|Soğuk Çene|Sığınak Takipçisi|Buz Kuyruk|Fırtına Avcısı|Donmuş Omurga|Vesuni Öncüsü|Buzul Yırtıcısı','Koku Peşinde|Kırağı İzi|Erzak Kokusu|Kar Perdesi|Soğuk Nefes|Fırtına Pususu|Buz Kapanı|Sığınak Ablukası|Donuk Pençe|Açlık Çağrısı|Kar Körlüğü|Son Soğuk'),
]
roles=[
 ('izci','İzci','tempo',[0,1,2,3,4,5,6,12,13,14,15,16,17,18,19,20,21], 'Ucuz birimleri önce oynar; açık enerji bırakıp ilk saldırıyı yoklar.','Erken alan hasarı ve ucuz engelleyiciler.','Oynanınca bir kart çek; bu tur ilk maliyet 2 veya altı aile kartı 1 ucuzlar.'),
 ('surucu','Sürücü','swarm',[0,1,2,3,4,5,6,7,12,13,16,17,18,19,20,22,23], 'En az üç birimle saldırır; tek büyük hedefe kaynak harcamaz.','Geniş alan temizliği; yaratılan küçük birimleri kes.','Oynanınca iki 1/1 aile yardımcısı yarat; bunlar turun sonunda kaybolur.'),
 ('avci','Avcı','mark',[2,3,4,5,6,7,8,12,13,14,15,17,18,19,20,21,22], 'Yaralı ve işaretli hedeflere odaklanır; kaldırma büyüsünü şampiyona saklar.','İşareti temizle; savunma öncesi şifa.','En düşük canlı düşmanı İşaretle; ilk aile vuruşu o hedefe +2 hasar.'),
 ('muhafiz','Muhafız','guard',[0,3,4,6,7,8,9,12,13,14,16,17,18,19,20,22,23], 'Savunma önceliklidir; komşu korumaları aynı sırada tutar.','Susturma ve farklı hedeflere bölünmüş hasar.','Oynanınca komşu aile birimlerine bu tur 2 geçici Can ver.'),
 ('duellocu','Düellocu','single',[1,2,4,5,7,8,9,13,14,15,16,17,18,19,20,21,23], 'Tek saldırganını güçlendirir; diğerlerini savunma için bırakır.','Güçlendirme bittikten sonra hedef kaldırma.','Bu tur yalnız saldırırsam +3 Saldırı; saldırı sonrasında bir tur tükenirim.'),
 ('kusatmaci','Kuşatmacı','siege',[3,5,6,7,8,9,10,12,14,15,16,17,18,19,20,21,23], 'Altıncı tura kadar ağır tehdit kurar; küçük tehditleri takas eder.','Altıncı turdan önce baskı; ağır kart maliyetini artır.','Üç tur sahada kaldıktan sonra saldırıda düşman özüne 3 hasar ver; sayaç görünür.'),
 ('pusucu','Pusucu','ambush',[0,1,2,4,5,6,8,12,13,14,15,16,17,18,20,21,22], 'Rakip saldırı hazırladıktan sonra kaynak harcar; sırayı acele etmez.','Pas geçerek tepkisini boşa çıkar; saldırı hazırlığında incele.','Düşman saldırı hazırlığında oynanabilir; saldıran birimin Saldırısını bu tur 2 azalt.'),
 ('buyucu','Ritüelci','spell',[0,2,4,7,8,9,11,12,13,14,15,16,17,18,20,22,23], 'Birim yerine büyü ekonomisini korur; iki büyülük komboyu bekler.','Sessizleştirme; karşı hamle enerjisini tüket.','Bir turda ikinci aile büyüsü oynanınca rastgelelik olmadan en soldaki düşmana 2 hasar.'),
 ('toplayici','Toplayıcı','resource',[0,1,3,5,6,7,9,12,13,14,16,17,18,19,20,21,22], 'Kart çeken düşük maliyetli birimleri korur; elini altının altında tutmaz.','Kaynak üreten birimleri öncelikli hedefle.','İlk aile biriminin ölümü sonrası bir aile kartı çek; tur başına bir kez.'),
 ('karsici','Karşıcı','counter',[1,2,3,4,6,8,10,12,13,14,15,16,17,18,19,21,23], 'Rakibin pahalı büyüsünü bekler; en az iki enerji açık bırakır.','Ucuz yem büyüleri; bir turda iki ayrı tehdit.','Maliyeti 3 veya daha az olan bir düşman büyüsünü iptal et; karşı tepki penceresi aç.'),
 ('dirilen','Dönen','recursion',[0,2,3,5,6,8,9,12,13,14,16,17,18,19,20,22,23], 'Kayıp birimlerini eline geri alır; ilk ölümü avantaj sayar.','Sürgün; geri alma kartı kullanılmadan baskı.','Bu tur ölen en düşük maliyetli aile birimini ele döndür; maliyetine +1 ekle.'),
 ('donusturucu','Dönüştürücü','evolve',[1,2,4,5,6,8,11,12,13,14,15,16,18,19,20,21,23], 'Üç aile kartından sonra ana tehdidi büyütür; kazanım sayacı görünürdür.','Üçüncü karttan önce ana tehdidi kaldır.','Üç aile kartı oynandığında bir kez +2/+2 kazan; kart yüzü değişir, sayaç sıfırlanmaz.'),
 ('tuketici','Tüketici','attrition',[0,1,3,4,7,9,10,12,13,14,15,16,17,18,20,21,23], 'Savunmada küçük takaslarla eli ve canı aşındırır.','Kart avantajı üret; uzun tur döngüsünden kaçın.','Bir düşmana 2 hasar ver; kendi özüne 1 hasar al. Aile kartı öldürürse bir kart çek.'),
 ('koruyucu','Koruyucu','support',[0,1,2,3,5,7,8,12,13,14,16,17,18,19,20,22,23], 'Destek birimini arka sırada korur; yaralıları saldırıya çıkarmaz.','Destek hedefini kaldır; komşuluk zincirini böl.','Tur sonunda en düşük canlı aile birimini 2 iyileştir; eşitlikte en soldakini seç.'),
 ('elit','Elit','mixed',[2,3,4,5,6,8,10,12,13,14,15,16,17,18,19,21,23], 'Önce savunma kurar, sonra maliyet 4+ tehditle saldırır; tek kombo yerine iki planı vardır.','Maliyetli tehdidi beklet; ilk savunma kaynağını zorla.','Oynanınca bir aile birimine bu tur +1/+2 ver ve bir kart çek; kendini seçemez.'),
 ('reis','Reis','boss',[0,3,5,6,7,9,11,12,13,14,15,16,17,18,20,22,23], 'Üç tur kurulumdan sonra komuta hücumu; yarı canda ikinci faza geçer.','Üçüncü tur öncesi hazırlık; faz geçişine iki cevap sakla.','Öz yarı cana ilk indiğinde iki 1/2 aile yardımcısı yarat; faz geçişi bir tur önceden uyarılır.'),
]
base_effects=['Oynanınca kendi ailemden bir birime bu tur +1 Saldırı ver.','Savunurken +1 Can; geçici Can tur sonunda kaldırılır.','Düşman saldırı hazırladığında bu tur +1 Saldırı.','Öldüğünde aynı aileden en soldaki müttefiki 1 iyileştir.','Oynanınca maliyet 2 veya altı aile kartını desteden ele al; kart açığa çıkar.','Saldırıda karşımdaki birime çatışmadan önce 1 hasar.','Bu tur ikinci aile birimiysen +1/+1.','Tur sonunda kendini 1 iyileştir.','Bir aile büyüsü oynandığında bu tur +1 Saldırı; turda bir kez.','Komşu aile birimi saldırırken ona bu tur +1 Can.','Siper: karşımdaki saldırgan öncelikle beni hedefler.','Saldırı sonrası bu tur tüken; vuruşta +2 Saldırı.']
spell_effects=['Bir birime 2 hasar.','Bir aile birimine bu tur +2 Saldırı.','Bir aile birimini 3 iyileştir.','Bir saldırganın Saldırısını bu tur 2 azalt.','Bir aile kartı çek.','Maliyeti 2 veya altı bir düşmanı bu tur saldırıdan alıkoy.','Bir aile birimini ele döndür; maliyeti bu tur 1 azalır.','İki düşmana 1’er hasar; hedefleri sırayla seç.','Bir aile birimine 2 geçici Can.','Bir düşman birimin metnini bu tur sustur.','Önceki tur ölen düşük maliyetli aile birimini ele döndür; +1 maliyet.','Maliyeti 4 veya daha fazla bir aile birimine bu tur +2/+1.']
cards=[];enemies=[];familydocs=[]
for fi,f in enumerate(families):
 fid,label,kind,places,refs,palette,passive,unitstr,spellstr=f;units=unitstr.split('|');spells=spellstr.split('|')
 fam={'id':fid,'name':label,'kind':kind,'regions':places.split(';'),'source_pages':refs,'provenance':'Roman teması; ayrıntılı birlik/istatistik/oynanış oyun önerisi' if refs else 'Atlas bestiary teması ve oyun genişlemesi','palette':palette,'passive_design':passive,'deck_restriction':{'allowed_family_ids':[fid],'neutral_allowed':False,'foreign_champions_allowed':False},'art_status':'12 görsellik ilk sanat seçkisine bak; tüm profiller için ayrı illüstrasyon henüz yok'}
 familydocs.append(fam)
 for i,name in enumerate(units+spells):
  unit=i<12;cost=1+(i%6) if unit else 1+((i-12)%4)
  cards.append({'id':f'{fid}-c{i:02}','family':fid,'name':name,'type':'birim' if unit else 'büyü','cost':cost,'attack':max(1,cost-1)+(i%2) if unit else None,'health':cost+1 if unit else None,'rules':base_effects[(i+fi)%12] if unit else spell_effects[(i-12+fi)%12],'timing':'birim' if unit else ('tepki' if i%3 else 'normal'),'status':'denge testi yapılmamış tasarım','art_prompt':f'Eruldin özgün kart illüstrasyonu: {name}; {label}; renk {palette}; özgün bölge atmosferi; yabancı fraksiyon simgesi yok.'})
 for ri,role in enumerate(roles):
  rid,rname,archetype,pool,ai,weak,ability=role;eid=f'{fid}-{rid}';sid=eid+'-signature';sigtype='büyü' if ri in [6,9,10,12] else 'birim'
  cards.append({'id':sid,'family':fid,'name':f'{rname} / {units[(ri+fi)%12]}','type':sigtype,'cost':2+(ri%4),'attack':2+ri%4 if sigtype=='birim' else None,'health':3+ri%4 if sigtype=='birim' else None,'rules':ability,'timing':'tepki' if ri in [6,9] else 'normal','exclusive_enemy_id':eid,'status':'denge testi yapılmamış tasarım','art_prompt':f'{label}, {rname}, {palette}, {units[(ri+fi)%12]}, aynı aileden; {archetype} rolünün görsel dili.'})
  # 14 doubled cards + 3 singles + 1 exclusive signature = 32. Role selection is different; never uses another family.
  deck=[{'card_id':f'{fid}-c{i:02}','count':2 if j<14 else 1} for j,i in enumerate(pool)]+[{'card_id':sid,'count':1}]
  tier= 'boss' if ri==15 else 'elite' if ri>=14 else 'normal'
  enemies.append({'id':eid,'name':f'{label} — {rname}','family':fid,'regions':places.split(';'),'tier':tier,'health':36 if tier=='boss' else 28 if tier=='elite' else 22,'archetype':archetype,'unique_signature':sid,'deck_size':32,'deck':deck,'ai_priority':ai,'counterplay':weak,'visible_passive':passive,'source_pages':refs,'story_role':'Oyun genişlemesi / düşman rolü; bu ailenin bütün üyeleri düşman değildir.','boss_phases':[{'at_health_fraction':0.5,'warning_turns':1,'effect':ability}] if tier=='boss' else [],'visual_variant':{'silhouette':rname,'equipment':units[(ri+fi)%12],'palette':palette},'art_status':'özel illüstrasyon üretim kuyruğunda','balance_status':'tasarım; oynanabilir motor içeriği değildir'})
lookup={c['id']:c for c in cards}
for e in enemies:
 assert sum(x['count'] for x in e['deck'])==32
 assert all(lookup[x['card_id']]['family']==e['family'] for x in e['deck'])
assert len({tuple(sorted((x['card_id'],x['count']) for x in e['deck'])) for e in enemies})==len(enemies)
dump(EN/'families.json',familydocs);dump(EN/'cards.json',cards);dump(EN/'enemy-decks.json',enemies)
with (EN/'enemy-catalog.csv').open('w',encoding='utf-8-sig',newline='') as h:
 w=csv.writer(h);w.writerow(['ID','Düşman','Aile','Bölgeler','Rol','Seviye','Can','Deste','İmza kartı','Oynanış','Karşı hamle','Kaynak sayfalar','Sanat durumu'])
 for e in enemies:w.writerow([e['id'],e['name'],e['family'],' / '.join(e['regions']),e['archetype'],e['tier'],e['health'],32,lookup[e['unique_signature']]['name'],e['ai_priority'],e['counterplay'],','.join(map(str,e['source_pages'])),e['art_status']])
with (EN/'all-deck-lists.txt').open('w',encoding='utf-8') as h:
 for e in enemies:
  h.write(f"\n{e['name']} [{e['id']}]\n32 kart / {e['archetype']} / yalnız {e['family']}\n")
  for item in e['deck']:h.write(f"{item['count']}x {lookup[item['card_id']]['name']}\n")
  h.write('İmza: '+lookup[e['unique_signature']]['rules']+'\nKarşı hamle: '+e['counterplay']+'\n')
# Local coordinates are an illustrated route layout, not assertions about Teolam geography.
chapters=[
 (1,'Yukarısı gibi aşağısı',[1,13],'Korvengrad',['Kör Aziz Katedrali','Katedral çıkışı','Karah sokakları','Teom çeliği','Fiona ile karşılaşma','Korvengrad’dan kaçış'],['karah-crawler','karah-armored','korvengrad-corrupt']),
 (2,'Küllerin Ağırlığı',[14,23],'Kül Tarlaları',['Kül Tarlaları','Yıkıntı sığınağı','Gece ateşi','Yaralı Fiona','Kırık Diş yaklaşımı','Geçit aşımı'],['karah-stalker','ash-scavenger','pass-raiders']),
 (3,"Koru’nun Paslı Kalbi",[24,38],'Koru',['Koru’ya giriş','Demirhane','Valerus’un talebi','Hücre / Akhenten','Torg’u etkisizleştir','Eski maden tünelleri'],['valerus-loyal','koru-jail','koru-forge']),
 (4,'Olasılıksız Yankı',[39,55],'Göz’ün Manastırı',['Dağ patikası','Manastır avlusu','Primus / ilk zaman çizgisi','Beyaz Yankı salonu','Avluya dönüş','Onbion ittifakı'],['pass-raiders','council','karah-stalker']),
 (5,'Koru',[56,66],'Koru',['Manastırdan iniş','Kuzey havalandırması','Mantar çiftlikleri','Gorn’un yardımı','Ziyafet baskını','Fiona / Gölge Yolu'],['koru-jail','koru-forge','valerus-loyal','council']),
 (6,'Kemik ve Kül',[67,85],'Kül Tarlaları',['Tensar’ın gölgesi','Koru’nun yıkılışı','Kül Tarlaları’na dönüş','Boru sığınağı','Kuzgunyuvası kontrolü','Paslı Kanca / yol planı'],['karah-armored','karah-crawler','ash-scavenger']),
 (7,'Taraflar',[86,100],'Kızıl Kale',['Fiona’nın hücresi','Kelebek muhafızları','Kızıl çizgi / Vesemir','Anzer Viole','Konsey / Primus / Shiro','Üç gece / kapalı oda'],['butterfly-guard','living-fortress','council']),
]
nodes=[];edges=[];last=None
for ch,title,refs,region,beats,allowed in chapters:
 for j,beat in enumerate(beats):
  nid=f'marcel-{ch:02}-{j+1:02}';kind='battle' if j in [0,1,3] else 'story'
  if (ch,j) in [(3,4),(4,2),(5,3),(5,5),(6,0),(6,4)] :kind='special'
  if ch==7:kind='story' if j in [0,2,3,4,5] else 'stealth'
  candidates=[e['id'] for e in enemies if e['family'] in allowed and e['tier']=='normal']
  objective='Karşılaşmayı tamamla.' if kind=='battle' else 'Diyaloğu ve sahne hedefini tamamla.'
  specials={(3,4):'Torg’u öldürmeden etkisizleştir; anahtarları al.',(4,2):'Yenilgiyle ilerleyen senaryolu karşılaşma; kalıcı yenilgi veya puan çiftliği değildir.',(5,3):'Gorn düşman değildir; buhar dikkat dağıtmasını seç.',(5,5):'Fiona’yı hedef alma; Gölge Yolu geçişiyle sahne tamamlanır.',(6,0):'Tensar’ın gölgesinden sağ çık; gerçek Tensar’ı öldürme hedefi yok.',(6,4):'Enfeksiyon kontrolünü geç; muhafızları öldürmek gerekli değildir.'}
  objective=specials.get((ch,j),objective)
  if ch==7:objective='Fiona bakış açısı: bilgi, saklanma ve hayatta kalma; bu bölümde kaleyi fethetme veya Kral’ı öldürme yok.'
  node={'id':nid,'title':beat,'chapter':ch,'chapter_title':title,'region':region,'type':kind,'source_page_range':refs,'story_evidence':'Roman sahnesi; kart karşılaşması ve seçimler oyun uyarlaması','world_xy':None,'route_layout_xy':[.08+j*.166,.88-(ch-1)*.122],'enemy_candidates':candidates if kind=='battle' else [],'objective':objective,'completed_checkpoint':(ch-1)*6+j+1,'spoiler_gate':ch,'map_state':'koru-destroyed' if ch>=6 else 'koru-intact','optional_battle':False}
  nodes.append(node)
  if last:edges.append({'from':last,'to':nid,'requires':'previous_completed'})
  last=nid
future=[{'id':'oluler-batakligi','name':'Ölüler Bataklığı','status':'82–84. sayfalarda planlanan rota; roman kesitinde Marcel henüz varmadı','world_xy':None,'playable_status':'genişleme önerisi; ana hikâye finali olarak açılmıyor'}]
dump(STORY/'marcel-campaign.json',{'scope':'100 sayfalık eldeki roman kesitine uyarlama','nodes':nodes,'edges':edges,'future_route':future,'ranking_design':{'primary':'en_yüksek_tamamlanmış_ana_hikâye_kontrol_noktası','secondary':'aynı kontrol noktasında sezon rekabet puanı','story_steps':42,'chapter_replays_increase_progress':False,'expeditions_unlock_story':False,'cutscene_skip_is_completion':False,'scripted_loss':'senaryo hedefiyle sunucuda bir kez doğrulanır; yeniden oynayarak ilerleme puanı üretmez','status':'tasarım; sunucuya bağlanmadı'}})
name_by_region={r['id']:r['name'] for r in atlas['regions']}
family_regions={'teomli':['korvengrad-watch','korvengrad-corrupt','valerus-loyal'],'shi-qra':['shi-qra-outlaws','koru-forge','karah-armored'],'serath':['pass-raiders','karah-crawler','ash-scavenger'],'aldemir':['forest-predators','marsh-visions','karah-stalker'],'val-teresh':['council','butterfly-guard','living-fortress'],'zagra-khur':['desert-hunters'],'ebedi-buzullar':['frost-predators']}
expeditions=[]
for r in atlas['regions']:
 center=next((p for p in atlas['points'] if p['id']==r['id']),None)
 exp={'region_id':r['id'],'name':r['name'],'center':{'x':center['x'],'y':center['y'],'space':center.get('uzay','m2026')} if center else None,'placement_note':'Merkez gerçek atlas POI’sidir; iç karşılaşmalar bölgesel rota önerisidir. Zağra Khur col uzayında gösterilir.','provenance':'Oyun genişlemesi; Marcel’in bu bölgeleri roman içinde gezdiği iddia edilmiyor.','unlock_after_story_checkpoint':6,'places':r['places'],'nodes':[]}
 for j,role in enumerate(roles):
  family=family_regions[r['id']][j%len(family_regions[r['id']])];eid=family+'-'+role[0];nodeid=r['id']+f'-exp-{j+1:02}'
  exp['nodes'].append({'id':nodeid,'index':j+1,'enemy_id':eid,'type':'boss' if j==15 else 'elite' if j==14 else 'battle','branches_to':[r['id']+f'-exp-{n+1:02}' for n in ([j+1,j+2] if j<13 else [j+1] if j<15 else [])],'layout_xy':[.1+(j%4)*.26,.15+(j//4)*.22],'world_xy':None,'reward_design':'Bölgesel kozmetik/keşif kaydı; ana hikâye ilerlemesi vermez.'})
 expeditions.append(exp)
dump(MAP/'data/regional-expeditions.json',expeditions)
dump(EN/'asset-bindings-v3.json',{'scope':'tasarım paketi veri bağlantıları; uygulama entegrasyonu değildir','defaults':{'card_unit_frame':'04-card-frames/unit.png','audio_attack':'09-audio/steel-impact.wav','vfx_hit':'06-vfx/animated-v2/impact-silver.glb'},'families':[{ 'family_id':f['id'],'portrait_asset':None,'art_status':'bekleyen tekil görsel','signature_card_ids':[e['unique_signature'] for e in enemies if e['family']==f['id']],'map_regions':f['regions'],'palette':f['palette'],'audio_note':'Mevcut v2 ses havuzundan seçim; ailelere özgü kayıt/mastering sonraki üretim.'} for f in familydocs]})
(STORY/'KANON-VE-UYARLAMA.txt').write_text('''ERULDİN / HARİTA VE KARŞILAŞMA PAKETİ V3

Kaynak coğrafya: Eruldin Destanı haritası sitesi. Kıyılar, POI koordinatları, arazi görselleri ve yükseklik verisi korunarak kopyalandı. Kaynak klasörde değişiklik yapılmadı.
Marcel yerlerinin dünya koordinatları bu atlasta yoktur. Yerel kampanya bir rota diyagramıdır; Teolam kıyılarına hayalî kesin koordinat eklenmedi. Zağra Khur’un col uzayı ana dünya uzayıyla karıştırılmaz.

ROMAN DAYANAKLARI
1–13 Korvengrad, katedral, Karahlar ve Fiona; 14–23 Kül Tarlaları/Kırık Diş; 24–38 Koru, Valerus, Borin, Torg, Akhenten ve kaçış; 39–55 manastır, Primus ve Yankılar; 56–66 Koru’ya dönüş, Gorn ve ziyafet; 67–85 Tensar’ın gölgesi, yıkım, Kuzgunyuvası; 86–100 Fiona bakış açısı ve Kızıl Kale.
Torg s.36 öldürülmez. Gorn s.61–62 yardımcıdır. Krovlar topluca düşman değildir.
Primus karşılaşmasının ilk çizgisi s.42–44 yenilgi ve Yankı geçişidir; oyuncu zaferi diye değiştirilmedi.
Fiona s.66 Gölge Yolu’ndan alınır; s.86–100 hayattadır. O bir düşman kartı/öldürme hedefi değildir.
Tensar s.67–70 görülen gölgedir; gerçek varlığı üç gün sonrası tehdididir. Yaratılan karanlık varlıklar s.72’den türetilmiştir.
Valerus s.69–70 ölümcül saldırıya uğrar; s.97–98 Anzer ölmediğini söyler. Bu süreklilik belirsizliği korunur, kesin öldü ya da tamamen iyileşti hükmü yoktur.
Paslı Kanca s.80’de gürültülü fakat müziksizdir; s.83–84 ozan girip Yitik Şafak ağıdını söyler. Ses atmosferi sahne aşamasına göre değişir.
Ölüler Bataklığı s.82–84 yol planıdır; Marcel’in henüz geçtiği sahne değildir. Genişleme olarak ayrılmıştır.
Kelebek işaretli ağızsız maskeler s.88; Anzer’in kelebekli siyah metal koltuğu s.94 ve kelebek s.98. Askerler Karah değildir.
Anzer Viole, Vesemir ve Shiro’nun gizli motivasyonları kesinleştirilmez. Kitabın kesit sonunda Kral ile final zaferi yoktur.

OYUN EKLEMELERİ
288 düşman profili, 720 kart tasarımı, desteler, yetenekler, istatistikler ve 112 bölgesel keşif karşılaşması oyun tasarımıdır. Atlasın kültür ve yaratık betimleri kendi notuna göre tasarım önerileri olabilir; roman kanonu diye kullanılmaz.
Korvengrad muhafız aileleri kullanıcı örneğinden geliştirilmiş oyun eklemesidir. İnsan/Krov birliğinin düşman olması rol ve sadakate bağlıdır.
Kadim Watcherlar sıradan düşman/deste/ganimet yapılmadı.
Bu paketteki yüzlerce düşman için ayrı bitmiş resim/model yoktur. Ayrı deste ve imza kartı verileri hazır; tüm kartların denge testi ve motor uygulaması yapılmadı.
''',encoding='utf-8')
dump(STORY/'content-validation.json',{'enemy_profiles':len(enemies),'families':len(familydocs),'cards':len(cards),'distinct_decks':len(enemies),'deck_size':32,'cross_family_cards':0,'exclusive_signature_cards':len(enemies),'story_checkpoints':len(nodes),'regional_encounters':sum(len(x['nodes']) for x in expeditions),'indexed_book_pages':len(pages),'balance_tests':'not run; design data only','source_preservation':all(sha(Path(c['source']))==c['sha256_source'] for c in copies)})
print(json.dumps({'copied_map_assets':len(copies),'enemies':len(enemies),'cards':len(cards),'story_nodes':len(nodes),'regional_nodes':112}))
