// GENERATED by tools/gen-campaign.mjs — chapters 5..59 (first 5 are canon).
// Node types: boss (10,20,...,60), tft grid bosses (8,18,...,58),
// elite (%10==4), normal. mutators[1] is the enemy's battle modifier.
export const CAMPAIGN = [
  {
    id: 5,
    seed: 1685,
    health: 17,
    tier: 1,
    type: "normal",
    act: 1,
    echo: "white",
    deck: [
      "g-av-kanli-surucusu-254",
      "maestro-borislav",
      "g-ruh-unutulmus-ritueli-309",
      "g-notr-toz-fisiltisi-162",
      "g-notr-kuzgunyuvasi-hurdacisi-193",
      "g-notr-kul-hurdacisi-170",
      "g-av-kuzey-ritueli-236",
      "g-av-bozkir-tazisi-258",
      "kuzgunyuvasi-gozcu",
      "g-av-bozkir-buyusu-270",
      "g-notr-kuzgunyuvasi-hurdacisi-193",
      "g-notr-pasli-zar-aticisi-157",
      "g-notr-kul-cobani-173",
      "g-av-pence-kurdu-241",
      "g-notr-kul-koleksiyoncusu-168",
      "g-notr-toz-koleksiyoncusu-183",
      "g-av-kanli-fisiltisi-243",
      "g-teom-goz-sovalyesi-126",
      "g-av-boynuz-canavari-250",
      "g-notr-toz-yemini-161"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "I. Perde — Sarnıç Mezarlığı",
      en: "Sarnıç Mezarlığı"
    },
    opponent: "Kül Serserileri",
    intro: {
      tr: "Korvengrad'ın külleri üstünde ilerliyorsun. {opp} yolu kesiyor.",
      en: "You advance over Korvengrad's ashes. {opp} blocks the road."
    },
    reward: {
      shards: 12
    },
    src: "[G]"
  },
  {
    id: 6,
    seed: 1822,
    health: 18,
    tier: 1,
    type: "tft",
    act: 1,
    echo: "teom",
    deck: [
      "g-konsey-kale-muhafizi-42",
      "g-serseri-sis-maskelisi-216",
      "g-konsey-kizil-muhafizi-52",
      "vesemir",
      "g-konsey-kan-zebellahi-47",
      "g-notr-tarlalar-gozcusu-171",
      "g-serseri-kor-kacagi-198",
      "g-konsey-sur-bedeli-51",
      "g-serseri-gri-pelerin-buyusu-228",
      "g-konsey-sur-zebellahi-72",
      "g-konsey-ferman-yemini-69",
      "g-serseri-yankisiz-maskelisi-230",
      "g-serseri-sis-yemini-207",
      "g-serseri-gece-kacagi-226",
      "g-av-kanli-okcusu-255",
      "kizil-cizgi",
      "g-serseri-yankisiz-yemini-203",
      "konsey-muhbiri",
      "g-serseri-gece-fisiltisi-208",
      "g-serseri-fisilti-golgesi-215"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "I. Perde — Ray Üstü",
      en: "Ray Üstü"
    },
    opponent: "Konsey Zaptiyesi",
    intro: {
      tr: "Korvengrad'ın külleri üstünde ilerliyorsun. {opp} yolu kesiyor.",
      en: "You advance over Korvengrad's ashes. {opp} blocks the road."
    },
    reward: {
      shards: 32
    },
    src: "[G]"
  },
  {
    id: 7,
    seed: 1959,
    health: 18,
    tier: 1,
    type: "normal",
    act: 1,
    echo: "ash",
    deck: [
      "g-av-kuzey-kurdu-248",
      "g-konsey-ferman-ritueli-43",
      "g-av-kanli-ritueli-245",
      "g-av-bozkir-yemini-242",
      "g-av-kuzey-surucusu-261",
      "teom-celigi",
      "g-notr-toz-hancisi-189",
      "g-av-kuzey-surucusu-261",
      "g-av-kurt-tazisi-266",
      "g-av-kuzey-kurdu-248",
      "g-av-boynuz-tazisi-249",
      "g-av-kurt-okcusu-239",
      "g-av-kurt-i-z-surucusu-237",
      "g-notr-tarlalar-gozcusu-171",
      "g-karah-katran-buyusu-79",
      "g-serseri-sis-fisiltisi-227",
      "g-notr-gri-hurdacisi-184",
      "g-av-pence-ritueli-244",
      "g-av-kurt-anlasmasi-264",
      "g-konsey-konsey-buyusu-40"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "I. Perde — Koru Eşiği",
      en: "Koru Eşiği"
    },
    opponent: "Bozkır Sürüsü",
    intro: {
      tr: "Korvengrad'ın külleri üstünde ilerliyorsun. {opp} yolu kesiyor.",
      en: "You advance over Korvengrad's ashes. {opp} blocks the road."
    },
    reward: {
      shards: 12
    },
    src: "[G]"
  },
  {
    id: 8,
    seed: 2096,
    health: 18,
    tier: 1,
    type: "normal",
    act: 1,
    echo: "white",
    deck: [
      "g-karah-siyah-fisiltisi-82",
      "g-karah-carpik-tohumu-90",
      "g-karah-siyah-tasiyicisi-94",
      "g-notr-tarlalar-cobani-179",
      "g-serseri-kor-kacagi-198",
      "g-karah-karah-zirhlisi-96",
      "g-serseri-kor-golgesi-223",
      "g-karah-katran-tohumu-103",
      "pasli-kanca",
      "g-notr-toz-bedeli-182",
      "g-karah-obsidyen-yavrusu-83",
      "g-karah-katran-tohumu-103",
      "g-karah-obsidyen-yavrusu-83",
      "g-karah-obsidyen-tasiyicisi-89",
      "g-notr-kul-hurdacisi-170",
      "g-karah-obsidyen-yavrusu-83",
      "g-karah-obsidyen-tasiyicisi-89",
      "g-notr-kuzgunyuvasi-hurdacisi-193",
      "g-karah-mor-yemini-91",
      "g-notr-kul-bedeli-178"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "I. Perde — Küllü Yol",
      en: "Küllü Yol"
    },
    opponent: "Karah Öncüsü",
    intro: {
      tr: "Korvengrad'ın külleri üstünde ilerliyorsun. {opp} yolu kesiyor.",
      en: "You advance over Korvengrad's ashes. {opp} blocks the road."
    },
    reward: {
      shards: 12
    },
    src: "[G]"
  },
  {
    id: 9,
    seed: 2233,
    health: 25,
    tier: 1,
    type: "boss",
    act: 1,
    echo: "teom",
    deck: [
      "g-teom-goz-buyusu-140",
      "g-konsey-sur-k-tibi-57",
      "g-direnis-mantar-dul-vereni-20",
      "g-konsey-kan-buyusu-46",
      "g-konsey-kale-zebellahi-41",
      "g-konsey-konsey-vergicisi-53",
      "g-teom-teom-vaizi-155",
      "g-serseri-sis-kacagi-199",
      "g-konsey-ferman-k-tibi-77",
      "g-serseri-kor-golgesi-223",
      "g-serseri-kor-bedeli-195",
      "g-serseri-yankisiz-maskelisi-230",
      "g-konsey-kan-zebellahi-47",
      "g-serseri-sis-maskelisi-216",
      "g-konsey-kizil-muhafizi-52",
      "g-konsey-sur-fisiltisi-59",
      "g-serseri-gri-pelerin-buyusu-228",
      "g-serseri-sis-kacagi-199",
      "g-serseri-gri-pelerin-maskelisi-205",
      "g-konsey-kizil-muhafizi-52",
      "valerus"
    ],
    mutators: [
      {},
      {
        hpBonus: 6,
        shield: 3
      }
    ],
    name: {
      tr: "Kırk Diş'in Kapıcısı",
      en: "Gatekeeper of Forty Teeth"
    },
    opponent: "Kapıcı Karga",
    intro: {
      tr: "Kalenin gölgesinde bekleyen şey adını sordu. Cevap vermedin.",
      en: "The thing in the castle's shadow asked your name. You didn't answer."
    },
    reward: {
      shards: 52
    },
    src: "[G]"
  },
  {
    id: 10,
    seed: 2370,
    health: 19,
    tier: 1,
    type: "normal",
    act: 1,
    echo: "ash",
    deck: [
      "g-serseri-kor-golgesi-223",
      "g-serseri-gece-fisiltisi-208",
      "g-konsey-sur-zebellahi-72",
      "g-serseri-kor-golgesi-223",
      "g-serseri-sis-pusucusu-218",
      "g-konsey-konsey-habercisi-65",
      "g-konsey-ferman-habercisi-76",
      "g-av-kurt-i-z-surucusu-237",
      "g-konsey-kizil-fisiltisi-68",
      "g-serseri-gri-pelerin-hirsizi-196",
      "g-serseri-yankisiz-maskelisi-230",
      "g-konsey-ferman-elcisi-56",
      "g-konsey-kale-fisiltisi-58",
      "g-konsey-kale-fisiltisi-58",
      "g-konsey-sur-fisiltisi-59",
      "g-konsey-sur-fisiltisi-59",
      "g-serseri-kor-kancalisi-211",
      "g-karah-carpik-tasiyicisi-111",
      "g-konsey-sur-k-tibi-57",
      "g-serseri-gece-bedeli-204"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "I. Perde — Ray Üstü",
      en: "Ray Üstü"
    },
    opponent: "Kızıl Muhafız",
    intro: {
      tr: "Korvengrad'ın külleri üstünde ilerliyorsun. {opp} yolu kesiyor.",
      en: "You advance over Korvengrad's ashes. {opp} blocks the road."
    },
    reward: {
      shards: 12
    },
    src: "[G]"
  },
  {
    id: 11,
    seed: 2507,
    health: 19,
    tier: 1,
    type: "normal",
    act: 1,
    echo: "white",
    deck: [
      "g-av-kanli-ritueli-245",
      "g-notr-kuzgunyuvasi-anlasmasi-159",
      "g-av-boynuz-canavari-250",
      "g-av-kurt-anlasmasi-264",
      "g-notr-kul-ritueli-185",
      "g-notr-gri-hurdacisi-184",
      "g-av-bozkir-ritueli-267",
      "g-av-kanli-fisiltisi-243",
      "g-av-kurt-buyusu-263",
      "g-av-kurt-okcusu-239",
      "g-av-boynuz-canavari-250",
      "g-av-kanli-fisiltisi-243",
      "g-ruh-unutulmus-ritueli-309",
      "g-notr-kul-yemini-175",
      "g-av-bozkir-buyusu-270",
      "g-av-kuzey-kurdu-248",
      "g-av-kurt-okcusu-239",
      "g-ruh-unutulmus-koru-masi-274",
      "g-notr-kul-hurdacisi-170",
      "g-ruh-unutulmus-yemini-306"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "I. Perde — Koru Eşiği",
      en: "Koru Eşiği"
    },
    opponent: "Avcı Birliği",
    intro: {
      tr: "Korvengrad'ın külleri üstünde ilerliyorsun. {opp} yolu kesiyor.",
      en: "You advance over Korvengrad's ashes. {opp} blocks the road."
    },
    reward: {
      shards: 12
    },
    src: "[G]"
  },
  {
    id: 12,
    seed: 2644,
    health: 20,
    tier: 1,
    type: "normal",
    act: 1,
    echo: "teom",
    deck: [
      "g-notr-toz-bedeli-182",
      "g-karah-katran-kulu-108",
      "g-karah-obsidyen-tohumu-99",
      "g-karah-carpik-filizi-87",
      "g-karah-obsidyen-yavrusu-83",
      "g-notr-pasli-bedeli-156",
      "g-ruh-unutulmus-ritueli-309",
      "g-teom-teom-sovalyesi-153",
      "g-karah-obsidyen-buyusu-104",
      "g-karah-obsidyen-bedeli-115",
      "g-karah-siyah-fisiltisi-82",
      "g-notr-toz-hancisi-189",
      "g-karah-katran-zirhlisi-78",
      "yozlasma-dokunusu",
      "g-karah-karah-surusu-113",
      "karah-yavru",
      "g-notr-kul-bedeli-178",
      "karah-yavru",
      "g-karah-mor-yemini-91",
      "karah-yavru"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "I. Perde — Küllü Yol",
      en: "Küllü Yol"
    },
    opponent: "Sürü Kulu",
    intro: {
      tr: "Korvengrad'ın külleri üstünde ilerliyorsun. {opp} yolu kesiyor.",
      en: "You advance over Korvengrad's ashes. {opp} blocks the road."
    },
    reward: {
      shards: 12
    },
    src: "[G]"
  },
  {
    id: 13,
    seed: 2781,
    health: 20,
    tier: 1,
    type: "elite",
    act: 1,
    echo: "ash",
    deck: [
      "g-av-bozkir-buyusu-270",
      "g-notr-toz-koleksiyoncusu-183",
      "g-notr-tarlalar-bedeli-191",
      "g-notr-tarlalar-cobani-179",
      "g-teom-beyaz-sovalyesi-139",
      "g-av-bozkir-ritueli-267",
      "g-notr-pasli-zar-aticisi-157",
      "g-notr-tarlalar-gozcusu-171",
      "g-notr-kul-yemini-175",
      "g-notr-toz-serseri-165",
      "g-av-boynuz-kurdu-257",
      "g-ruh-sisli-yankicisi-273",
      "g-notr-kuzgunyuvasi-zebellahi-166",
      "g-notr-kuzgunyuvasi-bedeli-192",
      "kuzgunyuvasi-gozcu",
      "g-notr-toz-koleksiyoncusu-183",
      "matrona-zarlari",
      "g-notr-pasli-bedeli-156",
      "g-notr-kul-ritueli-185",
      "g-notr-kuzgunyuvasi-hurdacisi-193"
    ],
    mutators: [
      {},
      {
        ozStart: 2
      }
    ],
    name: {
      tr: "I. Perde — Sarnıç Mezarlığı",
      en: "Sarnıç Mezarlığı"
    },
    opponent: "Tarla Haydutları",
    intro: {
      tr: "Rakip ilk turdan güçlü açılıyor.",
      en: "The foe opens strong from round one."
    },
    reward: {
      shards: 26
    },
    src: "[G]"
  },
  {
    id: 14,
    seed: 2918,
    health: 20,
    tier: 1,
    type: "normal",
    act: 1,
    echo: "white",
    deck: [
      "g-konsey-konsey-vergicisi-53",
      "g-serseri-gri-pelerin-buyusu-228",
      "g-konsey-ferman-k-tibi-77",
      "g-serseri-yankisiz-maskelisi-230",
      "g-konsey-kale-yemini-55",
      "g-konsey-kan-zebellahi-47",
      "g-serseri-kor-hirsizi-212",
      "g-serseri-sis-pusucusu-218",
      "g-serseri-yankisiz-buyusu-210",
      "g-serseri-yankisiz-hirsizi-197",
      "g-konsey-ferman-k-tibi-77",
      "g-serseri-yankisiz-hirsizi-197",
      "g-konsey-kan-buyusu-46",
      "g-serseri-sis-kancalisi-221",
      "konsey-muhbiri",
      "g-serseri-yankisiz-hirsizi-197",
      "g-konsey-kan-anlasmasi-48",
      "g-serseri-sis-bedeli-200",
      "g-konsey-kale-muhafizi-42",
      "g-konsey-kizil-yemini-49"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "I. Perde — Ray Üstü",
      en: "Ray Üstü"
    },
    opponent: "Sur Komutanı",
    intro: {
      tr: "Korvengrad'ın külleri üstünde ilerliyorsun. {opp} yolu kesiyor.",
      en: "You advance over Korvengrad's ashes. {opp} blocks the road."
    },
    reward: {
      shards: 12
    },
    src: "[G]"
  },
  {
    id: 15,
    seed: 3055,
    health: 21,
    tier: 1,
    type: "normal",
    act: 1,
    echo: "teom",
    deck: [
      "g-av-kanli-okcusu-255",
      "g-karah-carpik-tasiyicisi-111",
      "g-notr-kuzgunyuvasi-zebellahi-166",
      "g-av-boynuz-canavari-250",
      "g-notr-kuzgunyuvasi-yemini-160",
      "g-av-kurt-anlasmasi-264",
      "g-av-pence-tazisi-246",
      "g-av-kuzey-i-z-surucusu-238",
      "g-karah-obsidyen-bedeli-115",
      "g-av-kanli-yemini-260",
      "g-av-kurt-okcusu-239",
      "g-av-boynuz-canavari-250",
      "g-ruh-yanki-kalintisi-301",
      "g-av-kurt-canavari-235",
      "g-av-kurt-buyusu-263",
      "g-av-kuzey-i-z-surucusu-238",
      "g-notr-kul-hancisi-164",
      "g-av-bozkir-okcusu-262",
      "g-av-kuzey-surucusu-261",
      "g-av-kurt-okcusu-239"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "I. Perde — Koru Eşiği",
      en: "Koru Eşiği"
    },
    opponent: "Pençe Sürüsü",
    intro: {
      tr: "Korvengrad'ın külleri üstünde ilerliyorsun. {opp} yolu kesiyor.",
      en: "You advance over Korvengrad's ashes. {opp} blocks the road."
    },
    reward: {
      shards: 12
    },
    src: "[G]"
  },
  {
    id: 16,
    seed: 3192,
    health: 21,
    tier: 1,
    type: "tft",
    act: 1,
    echo: "ash",
    deck: [
      "g-notr-toz-hancisi-189",
      "g-karah-obsidyen-yavrusu-83",
      "g-notr-gri-hurdacisi-184",
      "g-notr-gri-serseri-172",
      "g-karah-katran-zirhlisi-78",
      "g-karah-katran-yemini-85",
      "g-karah-obsidyen-buyusu-104",
      "yozlasma-dokunusu",
      "g-notr-kul-koleksiyoncusu-168",
      "g-notr-toz-hancisi-189",
      "g-teom-kutsal-anlasmasi-125",
      "g-karah-obsidyen-ritueli-92",
      "g-karah-karah-tohumu-84",
      "obsidyen-sutun",
      "g-notr-toz-buyusu-188",
      "g-notr-toz-koleksiyoncusu-183",
      "g-notr-toz-zebellahi-177",
      "pasli-kanca",
      "karah-yavru",
      "g-notr-toz-koleksiyoncusu-183"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "I. Perde — Küllü Yol",
      en: "Küllü Yol"
    },
    opponent: "Yozlaşma Taşıyıcısı",
    intro: {
      tr: "Korvengrad'ın külleri üstünde ilerliyorsun. {opp} yolu kesiyor.",
      en: "You advance over Korvengrad's ashes. {opp} blocks the road."
    },
    reward: {
      shards: 32
    },
    src: "[G]"
  },
  {
    id: 17,
    seed: 3329,
    health: 21,
    tier: 1,
    type: "normal",
    act: 1,
    echo: "white",
    deck: [
      "g-av-kurt-surucusu-251",
      "g-notr-tarlalar-ritueli-187",
      "g-notr-tarlalar-gozcusu-171",
      "g-av-bozkir-tazisi-258",
      "g-av-kanli-okcusu-255",
      "g-notr-toz-zebellahi-177",
      "g-av-bozkir-okcusu-262",
      "g-notr-kuzgunyuvasi-koleksiyoncusu-174",
      "g-notr-kuzgunyuvasi-hurdacisi-193",
      "g-notr-toz-fisiltisi-162",
      "g-av-kuzey-surucusu-261",
      "g-notr-gri-hurdacisi-184",
      "g-notr-gri-serseri-172",
      "g-notr-toz-bedeli-182",
      "g-notr-toz-hancisi-189",
      "g-notr-toz-serseri-165",
      "g-av-pence-kurdu-241",
      "g-av-pence-okcusu-247",
      "g-notr-toz-hancisi-189",
      "g-notr-toz-zebellahi-177"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "I. Perde — Sarnıç Mezarlığı",
      en: "Sarnıç Mezarlığı"
    },
    opponent: "Kuzgunyuvası Çetesi",
    intro: {
      tr: "Korvengrad'ın külleri üstünde ilerliyorsun. {opp} yolu kesiyor.",
      en: "You advance over Korvengrad's ashes. {opp} blocks the road."
    },
    reward: {
      shards: 12
    },
    src: "[G]"
  },
  {
    id: 18,
    seed: 3466,
    health: 22,
    tier: 1,
    type: "normal",
    act: 1,
    echo: "teom",
    deck: [
      "g-serseri-gece-sokmasi-214",
      "g-konsey-kale-anlasmasi-60",
      "g-konsey-kan-k-tibi-75",
      "g-serseri-gri-pelerin-fisiltisi-217",
      "g-serseri-yankisiz-yemini-203",
      "g-konsey-kizil-muhafizi-52",
      "g-konsey-ferman-habercisi-76",
      "g-konsey-kan-anlasmasi-48",
      "g-serseri-gri-pelerin-ritueli-232",
      "g-serseri-sis-fisiltisi-227",
      "g-serseri-gece-kacagi-226",
      "g-konsey-kale-muhafizi-42",
      "g-konsey-konsey-buyusu-40",
      "g-konsey-ferman-elcisi-56",
      "g-konsey-kizil-muhafizi-52",
      "g-direnis-altin-sifacisi-35",
      "g-konsey-kan-buyusu-46",
      "g-serseri-yankisiz-bedeli-220",
      "vesemir",
      "g-karah-carpik-tasiyicisi-111"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "I. Perde — Ray Üstü",
      en: "Ray Üstü"
    },
    opponent: "Emir Muhafızı",
    intro: {
      tr: "Korvengrad'ın külleri üstünde ilerliyorsun. {opp} yolu kesiyor.",
      en: "You advance over Korvengrad's ashes. {opp} blocks the road."
    },
    reward: {
      shards: 12
    },
    src: "[G]"
  },
  {
    id: 19,
    seed: 3603,
    health: 32,
    tier: 1,
    type: "boss",
    act: 1,
    echo: "teom",
    deck: [
      "g-karah-mor-yemini-91",
      "g-karah-obsidyen-ritueli-92",
      "g-karah-carpik-emicisi-109",
      "g-karah-katran-filizi-116",
      "g-karah-siyah-fisiltisi-82",
      "g-karah-katran-kulu-108",
      "g-notr-toz-zebellahi-177",
      "g-karah-carpik-zirhlisi-95",
      "g-konsey-ferman-habercisi-76",
      "g-karah-siyah-tasiyicisi-94",
      "matrona-zarlari",
      "g-karah-mor-yemini-91",
      "g-karah-obsidyen-yavrusu-83",
      "g-karah-obsidyen-emicisi-81",
      "g-karah-siyah-tasiyicisi-94",
      "g-karah-katran-buyusu-79",
      "g-karah-siyah-fisiltisi-82",
      "g-notr-kul-cobani-173",
      "g-serseri-sis-maskelisi-216",
      "g-notr-tarlalar-gozcusu-171"
    ],
    mutators: [
      {},
      {
        hpBonus: 10,
        kwAll: [
          "canavar"
        ]
      }
    ],
    name: {
      tr: "Sürü Kraliçesi",
      en: "Swarm Queen"
    },
    opponent: "Karah Kraliçesi",
    intro: {
      tr: "Yavrular onun kanını taşıyor — hepsi aynı ağızdan konuşuyor.",
      en: "The spawn carry her blood — all speak with her mouth."
    },
    reward: {
      shards: 52
    },
    src: "[G]"
  },
  {
    id: 20,
    seed: 3740,
    health: 23,
    tier: 2,
    type: "normal",
    act: 2,
    echo: "white",
    deck: [
      "g-konsey-kizil-k-tibi-73",
      "g-konsey-kan-bedeli-50",
      "g-konsey-kan-bedeli-50",
      "g-konsey-kan-muhbiri-71",
      "g-konsey-kan-celladi-61",
      "gri-kelebek",
      "g-konsey-konsey-vergicisi-53",
      "g-serseri-fisilti-kacagi-229",
      "g-konsey-kan-habercisi-62",
      "g-konsey-kan-habercisi-62",
      "g-serseri-fisilti-kacagi-229",
      "g-konsey-sur-anlasmasi-67",
      "g-konsey-kan-anlasmasi-48",
      "g-serseri-yankisiz-yemini-203",
      "golge-yolu",
      "g-konsey-sur-k-tibi-57",
      "g-konsey-konsey-yemini-66",
      "g-konsey-konsey-buyusu-40",
      "g-konsey-sur-zebellahi-72",
      "g-konsey-konsey-yemini-66"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "II. Perde — Kızıl Sur",
      en: "Kızıl Sur"
    },
    opponent: "Konsey Zaptiyesi",
    intro: {
      tr: "Konsey topraklarındasın. {opp} seni bekliyordu.",
      en: "You are in Council territory. {opp} was expecting you."
    },
    reward: {
      shards: 16
    },
    src: "[G]"
  },
  {
    id: 21,
    seed: 3877,
    health: 23,
    tier: 2,
    type: "normal",
    act: 2,
    echo: "teom",
    deck: [
      "gri-kelebek",
      "g-serseri-gece-kancalisi-219",
      "g-serseri-kor-golgesi-223",
      "g-konsey-kan-fisiltisi-63",
      "g-serseri-yankisiz-bedeli-220",
      "g-konsey-kizil-buyusu-74",
      "g-serseri-yankisiz-hirsizi-197",
      "gri-kelebek",
      "g-serseri-gece-kacagi-226",
      "g-konsey-kan-muhbiri-71",
      "g-konsey-kan-habercisi-62",
      "g-serseri-fisilti-kacagi-229",
      "g-serseri-sis-kancalisi-221",
      "g-serseri-kor-hirsizi-212",
      "g-konsey-sur-yemini-39",
      "g-serseri-gri-pelerin-fisiltisi-217",
      "g-konsey-kizil-yemini-49",
      "g-konsey-kan-fisiltisi-63",
      "g-konsey-kan-muhafizi-44",
      "g-konsey-kan-celladi-61"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "II. Perde — Ferman Meydanı",
      en: "Ferman Meydanı"
    },
    opponent: "Sis Çetesi",
    intro: {
      tr: "Konsey topraklarındasın. {opp} seni bekliyordu.",
      en: "You are in Council territory. {opp} was expecting you."
    },
    reward: {
      shards: 16
    },
    src: "[G]"
  },
  {
    id: 22,
    seed: 4014,
    health: 23,
    tier: 2,
    type: "normal",
    act: 2,
    echo: "ash",
    deck: [
      "g-direnis-mantar-anlasmasi-37",
      "g-direnis-altin-bedeli-30",
      "g-direnis-ocak-anlasmasi-4",
      "g-konsey-kan-bedeli-50",
      "g-teom-beyaz-ritueli-148",
      "g-teom-goz-sovalyesi-126",
      "g-teom-teom-vaizi-155",
      "g-direnis-kopru-sifacisi-27",
      "teom-celigi",
      "g-teom-kutsal-bilgini-119",
      "g-direnis-kopru-tercumani-34",
      "g-teom-teom-bilgini-152",
      "g-direnis-koru-muhafizi-18",
      "hatirla",
      "gorn",
      "g-teom-goz-anlasmasi-123",
      "g-teom-kutsal-vaizi-129",
      "siginak",
      "g-direnis-kopru-yemini-7",
      "g-direnis-mantar-ascisi-0"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "II. Perde — Kırk Diş Avlusu",
      en: "Kırk Diş Avlusu"
    },
    opponent: "Koru Muhafızları",
    intro: {
      tr: "Konsey topraklarındasın. {opp} seni bekliyordu.",
      en: "You are in Council territory. {opp} was expecting you."
    },
    reward: {
      shards: 16
    },
    src: "[G]"
  },
  {
    id: 23,
    seed: 4151,
    health: 24,
    tier: 2,
    type: "elite",
    act: 2,
    echo: "white",
    deck: [
      "g-teom-goz-gozcusu-135",
      "g-teom-beyaz-muhafizi-142",
      "g-ruh-yanki-sesi-277",
      "g-ruh-unutulmus-koru-masi-274",
      "g-teom-goz-anlasmasi-123",
      "g-teom-teom-kesisi-144",
      "g-av-bozkir-okcusu-262",
      "g-ruh-hatira-yuzu-283",
      "g-teom-serlunar-kesisi-132",
      "g-ruh-unutulmus-buyusu-279",
      "g-teom-beyaz-bilgini-154",
      "g-ruh-akis-andici-299",
      "g-serseri-sis-kacagi-199",
      "g-ruh-unutulmus-fisiltisi-294",
      "g-ruh-unutulmus-andici-295",
      "g-teom-teom-sovalyesi-153",
      "g-ruh-unutulmus-buyusu-279",
      "g-ruh-yanki-kalintisi-301",
      "g-teom-manastir-vaizi-149",
      "g-ruh-sisli-ritueli-292"
    ],
    mutators: [
      {},
      {
        kwAll: [
          "ezici"
        ]
      }
    ],
    name: {
      tr: "II. Perde — Sis Sokağı",
      en: "Sis Sokağı"
    },
    opponent: "Göz'ün Keşişleri",
    intro: {
      tr: "Her biri dev — savunmayı aşıyorlar.",
      en: "Each one a giant — they roll over blockers."
    },
    reward: {
      shards: 30
    },
    src: "[G]"
  },
  {
    id: 24,
    seed: 4288,
    health: 24,
    tier: 2,
    type: "normal",
    act: 2,
    echo: "teom",
    deck: [
      "g-konsey-kan-muhafizi-44",
      "gri-kelebek",
      "g-konsey-kan-zebellahi-47",
      "g-serseri-fisilti-kacagi-229",
      "g-konsey-kan-celladi-61",
      "g-serseri-fisilti-kacagi-229",
      "g-konsey-sur-anlasmasi-67",
      "gri-kelebek",
      "g-konsey-kale-zebellahi-41",
      "g-konsey-kan-celladi-61",
      "g-serseri-gri-pelerin-yemini-213",
      "anzer",
      "g-konsey-kan-bedeli-50",
      "g-konsey-kan-muhafizi-44",
      "g-konsey-kale-fisiltisi-58",
      "g-serseri-gece-kacagi-226",
      "g-konsey-kan-buyusu-46",
      "g-konsey-kale-fisiltisi-58",
      "g-konsey-kan-muhbiri-71",
      "g-serseri-kor-kancalisi-211"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "II. Perde — Kızıl Sur",
      en: "Kızıl Sur"
    },
    opponent: "Kızıl Muhafız",
    intro: {
      tr: "Konsey topraklarındasın. {opp} seni bekliyordu.",
      en: "You are in Council territory. {opp} was expecting you."
    },
    reward: {
      shards: 16
    },
    src: "[G]"
  },
  {
    id: 25,
    seed: 4425,
    health: 24,
    tier: 2,
    type: "normal",
    act: 2,
    echo: "ash",
    deck: [
      "g-serseri-gri-pelerin-yemini-213",
      "g-serseri-gece-sokmasi-214",
      "g-serseri-fisilti-kacagi-229",
      "g-serseri-gece-buyusu-224",
      "g-serseri-gece-fisiltisi-208",
      "g-serseri-gece-kacagi-226",
      "g-serseri-fisilti-kacagi-229",
      "g-serseri-gri-pelerin-buyusu-228",
      "g-serseri-yankisiz-ritueli-233",
      "g-serseri-sis-maskelisi-216",
      "g-konsey-sur-bedeli-51",
      "g-konsey-kizil-k-tibi-73",
      "g-serseri-gri-pelerin-maskelisi-205",
      "anzer",
      "g-serseri-gri-pelerin-buyusu-228",
      "g-konsey-sur-anlasmasi-67",
      "g-serseri-kor-kacagi-198",
      "g-konsey-ferman-ritueli-43",
      "g-konsey-konsey-yemini-66",
      "g-konsey-kale-zebellahi-41"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "II. Perde — Ferman Meydanı",
      en: "Ferman Meydanı"
    },
    opponent: "Gölge Pusu",
    intro: {
      tr: "Konsey topraklarındasın. {opp} seni bekliyordu.",
      en: "You are in Council territory. {opp} was expecting you."
    },
    reward: {
      shards: 16
    },
    src: "[G]"
  },
  {
    id: 26,
    seed: 4562,
    health: 25,
    tier: 2,
    type: "tft",
    act: 2,
    echo: "white",
    deck: [
      "g-direnis-kopru-buyusu-23",
      "g-av-kanli-fisiltisi-243",
      "g-direnis-ocak-anlasmasi-4",
      "g-direnis-ocak-dul-vereni-33",
      "g-direnis-koru-sifacisi-1",
      "g-teom-serlunar-kesisi-132",
      "g-teom-teom-bilgini-152",
      "g-direnis-altin-tercumani-38",
      "torg",
      "g-direnis-altin-anlasmasi-25",
      "g-av-kuzey-ritueli-236",
      "g-teom-kutsal-muhafizi-117",
      "g-direnis-altin-tercumani-38",
      "g-direnis-kopru-sifacisi-27",
      "g-direnis-mantar-dul-vereni-20",
      "siginak",
      "g-teom-kutsal-anlasmasi-125",
      "fiona",
      "g-direnis-mantar-dul-vereni-20",
      "g-direnis-mantar-fisiltisi-14"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "II. Perde — Kırk Diş Avlusu",
      en: "Kırk Diş Avlusu"
    },
    opponent: "Ocak Devriyeleri",
    intro: {
      tr: "Konsey topraklarındasın. {opp} seni bekliyordu.",
      en: "You are in Council territory. {opp} was expecting you."
    },
    reward: {
      shards: 36
    },
    src: "[G]"
  },
  {
    id: 27,
    seed: 4699,
    health: 25,
    tier: 2,
    type: "normal",
    act: 2,
    echo: "teom",
    deck: [
      "g-teom-teom-bilgini-152",
      "g-ruh-sisli-yemini-298",
      "g-teom-beyaz-sovalyesi-139",
      "g-teom-teom-bilgini-152",
      "g-teom-beyaz-ritueli-148",
      "g-ruh-akis-feneri-305",
      "g-teom-teom-buyusu-128",
      "g-teom-goz-anlasmasi-123",
      "g-ruh-sisli-yemini-298",
      "g-teom-goz-anlasmasi-123",
      "g-teom-manastir-yemini-138",
      "g-teom-serlunar-demircisi-137",
      "g-direnis-ocak-tercumani-19",
      "g-ruh-sisli-yankicisi-273",
      "g-teom-teom-kesisi-144",
      "g-ruh-unutulmus-habercisi-297",
      "g-teom-teom-sovalyesi-153",
      "g-teom-kutsal-gozcusu-141",
      "g-karah-siyah-kulu-86",
      "g-karah-siyah-buyusu-100"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "II. Perde — Sis Sokağı",
      en: "Sis Sokağı"
    },
    opponent: "Manastır Devriyesi",
    intro: {
      tr: "Konsey topraklarındasın. {opp} seni bekliyordu.",
      en: "You are in Council territory. {opp} was expecting you."
    },
    reward: {
      shards: 16
    },
    src: "[G]"
  },
  {
    id: 28,
    seed: 4836,
    health: 25,
    tier: 2,
    type: "normal",
    act: 2,
    echo: "ash",
    deck: [
      "g-serseri-sis-maskelisi-216",
      "g-konsey-sur-bedeli-51",
      "g-serseri-kor-hirsizi-212",
      "g-konsey-sur-anlasmasi-67",
      "g-konsey-kizil-yemini-49",
      "g-konsey-kan-muhbiri-71",
      "g-serseri-gece-kacagi-226",
      "g-serseri-gri-pelerin-fisiltisi-217",
      "g-konsey-kan-zebellahi-47",
      "g-direnis-altin-tercumani-38",
      "g-serseri-sis-fisiltisi-227",
      "g-serseri-kor-kancalisi-211",
      "g-konsey-kale-muhafizi-42",
      "g-konsey-konsey-elcisi-45",
      "g-serseri-sis-kacagi-199",
      "g-konsey-kizil-buyusu-74",
      "g-serseri-sis-golgesi-206",
      "g-konsey-kan-anlasmasi-48",
      "g-serseri-sis-dilsizi-225",
      "g-konsey-kan-muhbiri-71"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "II. Perde — Kızıl Sur",
      en: "Kızıl Sur"
    },
    opponent: "Sur Komutanı",
    intro: {
      tr: "Konsey topraklarındasın. {opp} seni bekliyordu.",
      en: "You are in Council territory. {opp} was expecting you."
    },
    reward: {
      shards: 16
    },
    src: "[G]"
  },
  {
    id: 29,
    seed: 4973,
    health: 38,
    tier: 2,
    type: "boss",
    act: 2,
    echo: "teom",
    deck: [
      "g-serseri-gri-pelerin-maskelisi-205",
      "g-av-kanli-okcusu-255",
      "g-serseri-gece-kacagi-226",
      "g-konsey-kan-muhbiri-71",
      "g-konsey-sur-anlasmasi-67",
      "vesemir",
      "g-konsey-kale-anlasmasi-60",
      "g-konsey-kan-muhbiri-71",
      "g-serseri-kor-bedeli-195",
      "g-konsey-kan-muhafizi-44",
      "g-serseri-yankisiz-buyusu-210",
      "g-konsey-kale-yemini-55",
      "g-serseri-yankisiz-maskelisi-230",
      "g-serseri-fisilti-golgesi-215",
      "g-serseri-gri-pelerin-hirsizi-196",
      "g-konsey-kan-bedeli-50",
      "g-konsey-kan-habercisi-62",
      "g-serseri-gri-pelerin-maskelisi-205",
      "g-serseri-yankisiz-kacagi-209",
      "g-konsey-konsey-buyusu-40"
    ],
    mutators: [
      {},
      {
        hpBonus: 12,
        kwAll: [
          "golge"
        ]
      }
    ],
    name: {
      tr: "Sis Baronu",
      en: "Baron of Mist"
    },
    opponent: "Sis Baronu",
    intro: {
      tr: "Siste adım sesi yok; borç sesi var. Borcunu istemeye geldi.",
      en: "In the mist there are no footsteps — only debts. He came to collect."
    },
    reward: {
      shards: 56
    },
    src: "[G]"
  },
  {
    id: 30,
    seed: 5110,
    health: 26,
    tier: 2,
    type: "normal",
    act: 2,
    echo: "teom",
    deck: [
      "g-teom-serlunar-demircisi-137",
      "g-teom-serlunar-gozcusu-134",
      "beyaz-bosluk",
      "g-direnis-siginak-anlasmasi-21",
      "g-direnis-ocak-tercumani-19",
      "g-direnis-kopru-sifacisi-27",
      "g-notr-kuzgunyuvasi-bedeli-192",
      "g-direnis-kopru-ascisi-5",
      "torg",
      "g-direnis-altin-tercumani-38",
      "g-direnis-siginak-anlasmasi-21",
      "g-direnis-altin-isik-tasiyicisi-15",
      "g-direnis-kopru-kurucusu-6",
      "g-teom-serlunar-demircisi-137",
      "g-direnis-kopru-sifacisi-27",
      "g-teom-goz-muhafizi-124",
      "g-notr-tarlalar-ritueli-187",
      "g-direnis-koru-isik-tasiyicisi-17",
      "g-direnis-koru-muhafizi-18",
      "g-teom-beyaz-muhafizi-142"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "II. Perde — Kırk Diş Avlusu",
      en: "Kırk Diş Avlusu"
    },
    opponent: "Sığınak Birliği",
    intro: {
      tr: "Konsey topraklarındasın. {opp} seni bekliyordu.",
      en: "You are in Council territory. {opp} was expecting you."
    },
    reward: {
      shards: 16
    },
    src: "[G]"
  },
  {
    id: 31,
    seed: 5247,
    health: 26,
    tier: 2,
    type: "normal",
    act: 2,
    echo: "ash",
    deck: [
      "g-ruh-sisli-buyusu-304",
      "g-teom-manastir-vaizi-149",
      "g-teom-serlunar-vaizi-130",
      "g-teom-teom-ritueli-133",
      "g-teom-manastir-vaizi-149",
      "g-notr-tarlalar-cobani-179",
      "g-ruh-yanki-sesi-277",
      "g-teom-beyaz-yazmani-145",
      "g-teom-goz-anlasmasi-123",
      "g-ruh-sisli-feneri-289",
      "g-teom-serlunar-demircisi-137",
      "g-ruh-yanki-ritueli-293",
      "g-teom-manastir-fisiltisi-118",
      "g-teom-kutsal-gozcusu-141",
      "g-ruh-sisli-buyusu-304",
      "g-notr-pasli-bedeli-156",
      "g-teom-manastir-bedeli-146",
      "g-teom-serlunar-demircisi-137",
      "g-teom-teom-bilgini-152",
      "g-teom-teom-bilgini-152"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "II. Perde — Sis Sokağı",
      en: "Sis Sokağı"
    },
    opponent: "Teom Yargıcı",
    intro: {
      tr: "Konsey topraklarındasın. {opp} seni bekliyordu.",
      en: "You are in Council territory. {opp} was expecting you."
    },
    reward: {
      shards: 16
    },
    src: "[G]"
  },
  {
    id: 32,
    seed: 5384,
    health: 27,
    tier: 2,
    type: "normal",
    act: 2,
    echo: "white",
    deck: [
      "g-konsey-ferman-habercisi-76",
      "golge-yolu",
      "g-konsey-ferman-elcisi-56",
      "g-konsey-kan-zebellahi-47",
      "g-konsey-kizil-buyusu-74",
      "g-konsey-kan-bedeli-50",
      "g-serseri-sis-bedeli-200",
      "g-ruh-sisli-yankicisi-273",
      "g-serseri-fisilti-kacagi-229",
      "g-direnis-siginak-anlasmasi-21",
      "g-konsey-konsey-yemini-66",
      "g-konsey-ferman-elcisi-56",
      "g-konsey-konsey-yemini-66",
      "g-serseri-gece-bedeli-204",
      "g-serseri-gri-pelerin-sokmasi-222",
      "g-konsey-sur-anlasmasi-67",
      "g-konsey-konsey-fisiltisi-70",
      "g-konsey-ferman-habercisi-76",
      "g-serseri-fisilti-kacagi-229",
      "g-konsey-kan-muhafizi-44"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "II. Perde — Kızıl Sur",
      en: "Kızıl Sur"
    },
    opponent: "Emir Muhafızı",
    intro: {
      tr: "Konsey topraklarındasın. {opp} seni bekliyordu.",
      en: "You are in Council territory. {opp} was expecting you."
    },
    reward: {
      shards: 16
    },
    src: "[G]"
  },
  {
    id: 33,
    seed: 5521,
    health: 27,
    tier: 2,
    type: "elite",
    act: 2,
    echo: "teom",
    deck: [
      "g-konsey-sur-anlasmasi-67",
      "g-serseri-gri-pelerin-ritueli-232",
      "g-direnis-koru-muhafizi-18",
      "g-serseri-gri-pelerin-yemini-213",
      "g-serseri-yankisiz-bedeli-220",
      "g-serseri-kor-hirsizi-212",
      "g-serseri-fisilti-ritueli-202",
      "g-serseri-gece-kacagi-226",
      "g-serseri-fisilti-kacagi-229",
      "g-serseri-sis-bedeli-200",
      "g-serseri-kor-kacagi-198",
      "g-serseri-kor-bedeli-195",
      "g-konsey-ferman-elcisi-56",
      "g-serseri-fisilti-golgesi-215",
      "g-serseri-fisilti-kacagi-229",
      "g-konsey-kan-muhafizi-44",
      "g-teom-beyaz-yazmani-145",
      "g-serseri-kor-kacagi-198",
      "g-konsey-kan-anlasmasi-48",
      "g-serseri-gece-buyusu-224"
    ],
    mutators: [
      {},
      {
        hatira: 4
      }
    ],
    name: {
      tr: "II. Perde — Ferman Meydanı",
      en: "Ferman Meydanı"
    },
    opponent: "Kör Sokak Çetesi",
    intro: {
      tr: "Rakip savaşa nihai yeteneği dolu başlıyor.",
      en: "The foe begins with its ultimate charged."
    },
    reward: {
      shards: 30
    },
    src: "[G]"
  },
  {
    id: 34,
    seed: 5658,
    health: 27,
    tier: 2,
    type: "normal",
    act: 2,
    echo: "ash",
    deck: [
      "g-direnis-siginak-isik-tasiyicisi-2",
      "g-direnis-kopru-sifacisi-27",
      "g-direnis-siginak-anlasmasi-21",
      "g-direnis-kopru-ascisi-5",
      "g-direnis-altin-isik-tasiyicisi-15",
      "g-teom-manastir-fisiltisi-118",
      "g-direnis-ocak-anlasmasi-4",
      "g-teom-teom-kesisi-144",
      "g-direnis-siginak-anlasmasi-21",
      "g-direnis-koru-yemini-13",
      "g-direnis-mantar-tercumani-10",
      "g-direnis-siginak-ascisi-3",
      "g-direnis-kopru-sifacisi-27",
      "g-direnis-altin-ascisi-28",
      "g-direnis-kopru-buyusu-23",
      "g-direnis-koru-buyusu-11",
      "g-teom-serlunar-vaizi-130",
      "g-direnis-mantar-dul-vereni-20",
      "g-teom-goz-sovalyesi-126",
      "g-av-pence-okcusu-247"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "II. Perde — Kırk Diş Avlusu",
      en: "Kırk Diş Avlusu"
    },
    opponent: "Koru Yeminlileri",
    intro: {
      tr: "Konsey topraklarındasın. {opp} seni bekliyordu.",
      en: "You are in Council territory. {opp} was expecting you."
    },
    reward: {
      shards: 16
    },
    src: "[G]"
  },
  {
    id: 35,
    seed: 5795,
    health: 28,
    tier: 2,
    type: "normal",
    act: 2,
    echo: "white",
    deck: [
      "g-teom-teom-buyusu-128",
      "g-teom-goz-anlasmasi-123",
      "g-teom-teom-buyusu-128",
      "g-teom-teom-vaizi-155",
      "g-teom-beyaz-muhafizi-142",
      "g-konsey-kan-celladi-61",
      "g-karah-mor-yemini-91",
      "g-ruh-bosluk-yemini-303",
      "g-teom-goz-muhafizi-124",
      "g-ruh-akis-ritueli-311",
      "g-teom-manastir-demircisi-136",
      "g-teom-teom-bilgini-152",
      "g-ruh-unutulmus-andici-295",
      "g-teom-kutsal-vaizi-129",
      "g-teom-serlunar-gozcusu-134",
      "g-teom-teom-kesisi-144",
      "g-teom-serlunar-muhafizi-121",
      "g-teom-goz-sovalyesi-126",
      "g-notr-toz-fisiltisi-162",
      "g-teom-manastir-bilgini-122"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "II. Perde — Sis Sokağı",
      en: "Sis Sokağı"
    },
    opponent: "Beyaz Vaizler",
    intro: {
      tr: "Konsey topraklarındasın. {opp} seni bekliyordu.",
      en: "You are in Council territory. {opp} was expecting you."
    },
    reward: {
      shards: 16
    },
    src: "[G]"
  },
  {
    id: 36,
    seed: 5932,
    health: 28,
    tier: 2,
    type: "tft",
    act: 2,
    echo: "teom",
    deck: [
      "g-konsey-sur-k-tibi-57",
      "g-konsey-sur-bedeli-51",
      "g-konsey-kizil-k-tibi-73",
      "g-serseri-gri-pelerin-ritueli-232",
      "g-serseri-yankisiz-hirsizi-197",
      "g-serseri-yankisiz-yemini-203",
      "g-konsey-kan-muhbiri-71",
      "g-serseri-gri-pelerin-yemini-213",
      "g-konsey-ferman-ritueli-43",
      "g-konsey-kizil-muhafizi-52",
      "g-konsey-kan-habercisi-62",
      "g-serseri-yankisiz-yemini-203",
      "g-serseri-gri-pelerin-sokmasi-222",
      "g-serseri-sis-fisiltisi-227",
      "g-serseri-yankisiz-yemini-203",
      "g-konsey-sur-anlasmasi-67",
      "g-serseri-gri-pelerin-fisiltisi-217",
      "g-serseri-sis-bedeli-200",
      "g-konsey-konsey-habercisi-65",
      "golge-yolu"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "II. Perde — Kızıl Sur",
      en: "Kızıl Sur"
    },
    opponent: "Konsey Zaptiyesi",
    intro: {
      tr: "Konsey topraklarındasın. {opp} seni bekliyordu.",
      en: "You are in Council territory. {opp} was expecting you."
    },
    reward: {
      shards: 36
    },
    src: "[G]"
  },
  {
    id: 37,
    seed: 6069,
    health: 28,
    tier: 2,
    type: "normal",
    act: 2,
    echo: "ash",
    deck: [
      "g-serseri-sis-fisiltisi-227",
      "g-konsey-ferman-ritueli-43",
      "g-serseri-yankisiz-yemini-203",
      "valerus",
      "g-serseri-yankisiz-hirsizi-197",
      "anzer",
      "g-konsey-sur-yemini-39",
      "g-serseri-fisilti-kacagi-229",
      "g-serseri-sis-yemini-207",
      "g-konsey-kizil-k-tibi-73",
      "g-serseri-sis-kacagi-199",
      "g-konsey-kale-anlasmasi-60",
      "g-direnis-altin-tercumani-38",
      "g-konsey-kale-yemini-55",
      "g-av-kuzey-i-z-surucusu-238",
      "g-serseri-gece-kacagi-226",
      "g-konsey-konsey-buyusu-40",
      "g-serseri-kor-hirsizi-212",
      "g-konsey-kan-anlasmasi-48",
      "g-konsey-kan-k-tibi-75"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "II. Perde — Ferman Meydanı",
      en: "Ferman Meydanı"
    },
    opponent: "Maskeli Olanlar",
    intro: {
      tr: "Konsey topraklarındasın. {opp} seni bekliyordu.",
      en: "You are in Council territory. {opp} was expecting you."
    },
    reward: {
      shards: 16
    },
    src: "[G]"
  },
  {
    id: 38,
    seed: 6206,
    health: 29,
    tier: 2,
    type: "normal",
    act: 2,
    echo: "white",
    deck: [
      "g-direnis-altin-sifacisi-35",
      "g-av-kurt-tazisi-266",
      "g-direnis-altin-bedeli-30",
      "g-direnis-ocak-kurucusu-26",
      "g-teom-teom-kesisi-144",
      "g-direnis-kopru-buyusu-23",
      "g-teom-beyaz-bilgini-154",
      "g-direnis-kopru-ritueli-24",
      "g-direnis-siginak-isik-tasiyicisi-2",
      "g-direnis-mantar-ritueli-36",
      "g-direnis-ocak-tercumani-19",
      "g-direnis-kopru-ascisi-5",
      "g-direnis-altin-sifacisi-35",
      "g-direnis-altin-fisiltisi-22",
      "g-direnis-koru-yemini-13",
      "g-direnis-kopru-buyusu-23",
      "g-teom-beyaz-bilgini-154",
      "g-direnis-koru-buyusu-11",
      "g-direnis-ocak-tercumani-19",
      "g-notr-toz-hancisi-189"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "II. Perde — Kırk Diş Avlusu",
      en: "Kırk Diş Avlusu"
    },
    opponent: "Koru Muhafızları",
    intro: {
      tr: "Konsey topraklarındasın. {opp} seni bekliyordu.",
      en: "You are in Council territory. {opp} was expecting you."
    },
    reward: {
      shards: 16
    },
    src: "[G]"
  },
  {
    id: 39,
    seed: 6343,
    health: 43,
    tier: 2,
    type: "boss",
    act: 2,
    echo: "teom",
    deck: [
      "g-serseri-gri-pelerin-hirsizi-196",
      "g-ruh-hatira-yuzu-283",
      "g-teom-goz-anlasmasi-123",
      "g-ruh-sisli-yemini-298",
      "g-konsey-konsey-vergicisi-53",
      "g-konsey-kan-muhafizi-44",
      "g-teom-teom-buyusu-128",
      "g-teom-manastir-yemini-138",
      "g-ruh-unutulmus-yemini-306",
      "g-ruh-hatira-yuzu-283",
      "g-teom-teom-vaizi-155",
      "g-konsey-kan-muhbiri-71",
      "g-teom-kutsal-bilgini-119",
      "g-teom-goz-gozcusu-135",
      "g-teom-teom-sovalyesi-153",
      "g-teom-goz-sovalyesi-126",
      "g-direnis-kopru-yemini-7",
      "g-teom-teom-kesisi-144",
      "g-teom-beyaz-muhafizi-142",
      "serlunar-bilgin"
    ],
    mutators: [
      {},
      {
        hpBonus: 14,
        kwAll: [
          "celik"
        ],
        shield: 4
      }
    ],
    name: {
      tr: "Teom İnkarı",
      en: "The Teom Denial"
    },
    opponent: "İnkar Şövalyesi",
    intro: {
      tr: "Çelik kanmadan konuşamaz; o konuşmadan duramaz.",
      en: "Steel cannot speak unanswered; he cannot stand silent."
    },
    reward: {
      shards: 56
    },
    src: "[G]"
  },
  {
    id: 40,
    seed: 6480,
    health: 30,
    tier: 3,
    type: "normal",
    act: 3,
    echo: "ash",
    deck: [
      "g-karah-siyah-kulu-86",
      "g-karah-siyah-anlasmasi-112",
      "g-karah-siyah-buyusu-100",
      "g-notr-gri-hurdacisi-184",
      "g-karah-mor-yemini-91",
      "g-notr-gri-serseri-172",
      "g-karah-obsidyen-kulu-107",
      "g-karah-katran-buyusu-79",
      "g-karah-siyah-tasiyicisi-94",
      "g-notr-toz-yemini-161",
      "g-notr-tarlalar-gozcusu-171",
      "g-karah-siyah-kulu-86",
      "g-direnis-altin-tercumani-38",
      "g-notr-kuzgunyuvasi-yemini-160",
      "g-karah-obsidyen-ritueli-92",
      "g-teom-teom-bilgini-152",
      "g-karah-obsidyen-ritueli-92",
      "g-notr-toz-koleksiyoncusu-183",
      "g-notr-kul-buyusu-180",
      "g-konsey-ferman-elcisi-56"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "III. Perde — Mor Damar Geçidi",
      en: "Mor Damar Geçidi"
    },
    opponent: "Mor Sürü",
    intro: {
      tr: "Mor damarlar taşların arasında atıyor. {opp} son direnişini kurdu.",
      en: "Violet veins pulse in the stone. {opp} has made its last stand."
    },
    reward: {
      shards: 20
    },
    src: "[G]"
  },
  {
    id: 41,
    seed: 6617,
    health: 30,
    tier: 3,
    type: "normal",
    act: 3,
    echo: "white",
    deck: [
      "g-ruh-sisli-yemini-298",
      "g-teom-serlunar-kesisi-132",
      "g-teom-manastir-sovalyesi-120",
      "g-ruh-hatira-yuzu-283",
      "g-teom-serlunar-gozcusu-134",
      "g-teom-teom-buyusu-128",
      "g-ruh-unutulmus-feneri-282",
      "g-ruh-sisli-buyusu-304",
      "g-ruh-yanki-andici-310",
      "g-teom-kutsal-gozcusu-141",
      "g-teom-goz-anlasmasi-123",
      "g-ruh-bosluk-feneri-288",
      "g-direnis-altin-tercumani-38",
      "g-konsey-kan-celladi-61",
      "g-ruh-bosluk-yemini-303",
      "g-teom-manastir-vaizi-149",
      "g-teom-goz-muhafizi-124",
      "g-ruh-akis-ritueli-311",
      "g-ruh-unutulmus-habercisi-297",
      "g-teom-beyaz-muhafizi-142"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "III. Perde — Obsidyen Çukur",
      en: "Obsidyen Çukur"
    },
    opponent: "Yankı Ağıtçıları",
    intro: {
      tr: "Mor damarlar taşların arasında atıyor. {opp} son direnişini kurdu.",
      en: "Violet veins pulse in the stone. {opp} has made its last stand."
    },
    reward: {
      shards: 20
    },
    src: "[G]"
  },
  {
    id: 42,
    seed: 6754,
    health: 30,
    tier: 3,
    type: "normal",
    act: 3,
    echo: "teom",
    deck: [
      "g-konsey-kan-anlasmasi-48",
      "g-serseri-sis-kancalisi-221",
      "g-serseri-gece-buyusu-224",
      "g-serseri-kor-hirsizi-212",
      "g-konsey-konsey-yemini-66",
      "g-serseri-yankisiz-bedeli-220",
      "g-serseri-sis-yemini-207",
      "g-serseri-fisilti-kacagi-229",
      "g-serseri-sis-golgesi-206",
      "g-konsey-kizil-buyusu-74",
      "g-konsey-kan-celladi-61",
      "g-konsey-kan-fisiltisi-63",
      "g-konsey-kizil-muhafizi-52",
      "g-konsey-kan-celladi-61",
      "g-konsey-kan-muhafizi-44",
      "g-serseri-sis-maskelisi-216",
      "g-serseri-sis-fisiltisi-227",
      "g-serseri-gece-kacagi-226",
      "g-serseri-fisilti-kacagi-229",
      "g-serseri-gece-sokmasi-214"
    ],
    mutators: [
      {},
      {
        shield: 2
      }
    ],
    name: {
      tr: "III. Perde — Yankı Vadisi",
      en: "Yankı Vadisi"
    },
    opponent: "Sis Çetesi",
    intro: {
      tr: "Mor damarlar taşların arasında atıyor. {opp} son direnişini kurdu.",
      en: "Violet veins pulse in the stone. {opp} has made its last stand."
    },
    reward: {
      shards: 20
    },
    src: "[G]"
  },
  {
    id: 43,
    seed: 6891,
    health: 31,
    tier: 3,
    type: "elite",
    act: 3,
    echo: "ash",
    deck: [
      "g-konsey-kan-celladi-61",
      "g-teom-goz-fisiltisi-150",
      "g-teom-kutsal-vaizi-129",
      "g-teom-serlunar-kesisi-132",
      "g-konsey-sur-anlasmasi-67",
      "g-teom-kutsal-anlasmasi-125",
      "g-teom-goz-gozcusu-135",
      "g-ruh-bosluk-sesi-276",
      "g-teom-goz-anlasmasi-123",
      "g-ruh-akis-koru-masi-287",
      "g-teom-beyaz-bilgini-154",
      "g-teom-teom-kesisi-144",
      "g-ruh-akis-koru-masi-287",
      "g-ruh-akis-andici-299",
      "g-teom-teom-bilgini-152",
      "teom-celigi",
      "g-teom-goz-gozcusu-135",
      "g-ruh-unutulmus-buyusu-279",
      "g-teom-manastir-yemini-138",
      "g-teom-kutsal-vaizi-129"
    ],
    mutators: [
      {},
      {
        kwAll: [
          "koruyucu"
        ]
      }
    ],
    name: {
      tr: "III. Perde — Son Sur",
      en: "Son Sur"
    },
    opponent: "Göz'ün Keşişleri",
    intro: {
      tr: "Duvar gibi dizilmişler — önüne geçemezsin.",
      en: "A wall of shields — you cannot slip past."
    },
    reward: {
      shards: 34
    },
    src: "[G]"
  },
  {
    id: 44,
    seed: 7028,
    health: 31,
    tier: 3,
    type: "normal",
    act: 3,
    echo: "white",
    deck: [
      "g-karah-carpik-surusu-97",
      "g-teom-serlunar-demircisi-137",
      "g-notr-kul-koleksiyoncusu-168",
      "g-karah-siyah-anlasmasi-112",
      "g-notr-kul-cobani-173",
      "g-karah-obsidyen-bedeli-115",
      "g-karah-siyah-anlasmasi-112",
      "g-karah-siyah-fisiltisi-82",
      "g-notr-pasli-gozcusu-194",
      "g-karah-siyah-yavrusu-88",
      "g-karah-katran-buyusu-79",
      "g-notr-pasli-zar-aticisi-157",
      "g-karah-carpik-tohumu-90",
      "g-karah-obsidyen-ritueli-92",
      "g-notr-kul-buyusu-180",
      "g-notr-pasli-gozcusu-194",
      "g-notr-toz-yemini-161",
      "g-karah-katran-kulu-108",
      "g-notr-kul-buyusu-180",
      "g-karah-carpik-surusu-97"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "III. Perde — Mor Damar Geçidi",
      en: "Mor Damar Geçidi"
    },
    opponent: "Karah Öncüsü",
    intro: {
      tr: "Mor damarlar taşların arasında atıyor. {opp} son direnişini kurdu.",
      en: "Violet veins pulse in the stone. {opp} has made its last stand."
    },
    reward: {
      shards: 20
    },
    src: "[G]"
  },
  {
    id: 45,
    seed: 7165,
    health: 31,
    tier: 3,
    type: "normal",
    act: 3,
    echo: "teom",
    deck: [
      "g-ruh-yanki-andici-310",
      "g-ruh-unutulmus-feneri-282",
      "g-ruh-unutulmus-kalintisi-278",
      "g-ruh-yanki-andici-310",
      "g-ruh-unutulmus-buyusu-279",
      "g-ruh-bosluk-habercisi-302",
      "g-teom-goz-anlasmasi-123",
      "g-direnis-mantar-tercumani-10",
      "g-ruh-hatira-feneri-280",
      "g-teom-teom-vaizi-155",
      "g-teom-goz-anlasmasi-123",
      "g-ruh-sisli-ritueli-292",
      "g-teom-teom-kesisi-144",
      "g-ruh-akis-habercisi-285",
      "g-teom-teom-bilgini-152",
      "g-teom-teom-ritueli-133",
      "g-serseri-yankisiz-buyusu-210",
      "g-ruh-unutulmus-yemini-306",
      "g-serseri-gri-pelerin-hirsizi-196",
      "g-teom-manastir-vaizi-149"
    ],
    mutators: [
      {},
      {
        shield: 2
      }
    ],
    name: {
      tr: "III. Perde — Obsidyen Çukur",
      en: "Obsidyen Çukur"
    },
    opponent: "Hatıra Korucuları",
    intro: {
      tr: "Mor damarlar taşların arasında atıyor. {opp} son direnişini kurdu.",
      en: "Violet veins pulse in the stone. {opp} has made its last stand."
    },
    reward: {
      shards: 20
    },
    src: "[G]"
  },
  {
    id: 46,
    seed: 7302,
    health: 32,
    tier: 3,
    type: "tft",
    act: 3,
    echo: "ash",
    deck: [
      "g-serseri-yankisiz-ritueli-233",
      "g-direnis-siginak-ascisi-3",
      "g-serseri-yankisiz-buyusu-210",
      "g-serseri-sis-dilsizi-225",
      "g-serseri-gri-pelerin-buyusu-228",
      "g-karah-siyah-yavrusu-88",
      "g-serseri-sis-pusucusu-218",
      "karah-suru",
      "g-konsey-kan-celladi-61",
      "g-serseri-sis-dilsizi-225",
      "g-serseri-fisilti-kacagi-229",
      "gri-kelebek",
      "g-karah-obsidyen-tohumu-99",
      "g-konsey-sur-fisiltisi-59",
      "g-serseri-gri-pelerin-fisiltisi-217",
      "g-serseri-sis-pusucusu-218",
      "g-serseri-sis-golgesi-206",
      "g-konsey-kan-k-tibi-75",
      "g-serseri-gece-kancalisi-219",
      "g-teom-manastir-sovalyesi-120"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "III. Perde — Yankı Vadisi",
      en: "Yankı Vadisi"
    },
    opponent: "Gölge Pusu",
    intro: {
      tr: "Mor damarlar taşların arasında atıyor. {opp} son direnişini kurdu.",
      en: "Violet veins pulse in the stone. {opp} has made its last stand."
    },
    reward: {
      shards: 40
    },
    src: "[G]"
  },
  {
    id: 47,
    seed: 7439,
    health: 32,
    tier: 3,
    type: "normal",
    act: 3,
    echo: "white",
    deck: [
      "g-teom-serlunar-gozcusu-134",
      "g-teom-kutsal-anlasmasi-125",
      "g-teom-beyaz-sovalyesi-139",
      "g-teom-goz-sovalyesi-126",
      "g-teom-goz-buyusu-140",
      "g-ruh-unutulmus-ritueli-309",
      "g-teom-goz-buyusu-140",
      "g-teom-teom-buyusu-128",
      "g-teom-manastir-fisiltisi-118",
      "g-ruh-hatira-anlasmasi-291",
      "g-ruh-sisli-ritueli-292",
      "g-teom-goz-anlasmasi-123",
      "g-ruh-unutulmus-feneri-282",
      "g-teom-goz-fisiltisi-150",
      "g-teom-teom-ritueli-133",
      "g-teom-goz-fisiltisi-150",
      "g-ruh-akis-ritueli-311",
      "g-teom-beyaz-yazmani-145",
      "g-teom-teom-kesisi-144",
      "g-teom-manastir-yemini-138"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "III. Perde — Son Sur",
      en: "Son Sur"
    },
    opponent: "Manastır Devriyesi",
    intro: {
      tr: "Mor damarlar taşların arasında atıyor. {opp} son direnişini kurdu.",
      en: "Violet veins pulse in the stone. {opp} has made its last stand."
    },
    reward: {
      shards: 20
    },
    src: "[G]"
  },
  {
    id: 48,
    seed: 7576,
    health: 32,
    tier: 3,
    type: "normal",
    act: 3,
    echo: "teom",
    deck: [
      "g-notr-toz-yemini-161",
      "g-karah-carpik-emicisi-109",
      "g-karah-siyah-fisiltisi-82",
      "g-karah-obsidyen-bedeli-115",
      "g-karah-katran-filizi-116",
      "g-teom-teom-bilgini-152",
      "g-karah-karah-surusu-113",
      "g-karah-katran-surusu-93",
      "g-notr-kul-buyusu-180",
      "g-karah-mor-yemini-91",
      "g-karah-katran-tasiyicisi-80",
      "g-karah-karah-emicisi-110",
      "g-notr-gri-koleksiyoncusu-158",
      "g-karah-carpik-filizi-87",
      "g-notr-kuzgunyuvasi-yemini-160",
      "g-karah-obsidyen-bedeli-115",
      "g-notr-kuzgunyuvasi-koleksiyoncusu-174",
      "g-karah-siyah-fisiltisi-82",
      "g-karah-carpik-filizi-87",
      "g-karah-obsidyen-bedeli-115"
    ],
    mutators: [
      {},
      {
        shield: 2
      }
    ],
    name: {
      tr: "III. Perde — Mor Damar Geçidi",
      en: "Mor Damar Geçidi"
    },
    opponent: "Sürü Kulu",
    intro: {
      tr: "Mor damarlar taşların arasında atıyor. {opp} son direnişini kurdu.",
      en: "Violet veins pulse in the stone. {opp} has made its last stand."
    },
    reward: {
      shards: 20
    },
    src: "[G]"
  },
  {
    id: 49,
    seed: 7713,
    health: 49,
    tier: 3,
    type: "boss",
    act: 3,
    echo: "white",
    deck: [
      "g-teom-goz-anlasmasi-123",
      "g-ruh-unutulmus-andici-295",
      "beyaz-bosluk",
      "g-ruh-unutulmus-ritueli-309",
      "g-ruh-yanki-yuzu-308",
      "g-ruh-unutulmus-yemini-306",
      "g-ruh-akis-bedeli-307",
      "g-ruh-akis-feneri-305",
      "g-ruh-yanki-ritueli-293",
      "g-ruh-sisli-kalintisi-296",
      "g-ruh-akis-koru-masi-287",
      "g-ruh-bosluk-sesi-276",
      "g-ruh-hatira-yuzu-283",
      "g-ruh-bosluk-yankicisi-290",
      "g-teom-serlunar-demircisi-137",
      "g-teom-kutsal-sovalyesi-127",
      "g-teom-beyaz-demircisi-131",
      "g-ruh-bosluk-yankicisi-290",
      "g-teom-manastir-yemini-138",
      "g-ruh-bosluk-feneri-288"
    ],
    mutators: [
      {},
      {
        hpBonus: 16,
        kwAll: [
          "yanki"
        ],
        hatira: 6
      }
    ],
    name: {
      tr: "Yankı Düğümü",
      en: "Echo Knot"
    },
    opponent: "Düğüm",
    intro: {
      tr: "Burada ölümler geri alınıyor — ama bedeli artıyor.",
      en: "Here deaths are unmade — but the price grows."
    },
    reward: {
      shards: 60
    },
    src: "[G]"
  },
  {
    id: 50,
    seed: 7850,
    health: 33,
    tier: 3,
    type: "normal",
    act: 3,
    echo: "white",
    deck: [
      "g-serseri-sis-pusucusu-218",
      "g-serseri-sis-fisiltisi-227",
      "g-serseri-sis-kacagi-199",
      "g-serseri-yankisiz-kacagi-209",
      "g-konsey-ferman-habercisi-76",
      "g-konsey-ferman-elcisi-56",
      "g-serseri-fisilti-kacagi-229",
      "g-serseri-yankisiz-maskelisi-230",
      "g-serseri-fisilti-kacagi-229",
      "g-serseri-gri-pelerin-yemini-213",
      "g-serseri-gece-buyusu-224",
      "g-serseri-yankisiz-buyusu-210",
      "g-serseri-kor-kacagi-198",
      "g-konsey-kan-zebellahi-47",
      "g-serseri-gece-kacagi-226",
      "g-serseri-gri-pelerin-hirsizi-196",
      "g-serseri-yankisiz-hirsizi-197",
      "g-konsey-kan-habercisi-62",
      "g-serseri-gece-kacagi-226",
      "g-serseri-fisilti-golgesi-215"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "III. Perde — Yankı Vadisi",
      en: "Yankı Vadisi"
    },
    opponent: "Kör Sokak Çetesi",
    intro: {
      tr: "Mor damarlar taşların arasında atıyor. {opp} son direnişini kurdu.",
      en: "Violet veins pulse in the stone. {opp} has made its last stand."
    },
    reward: {
      shards: 20
    },
    src: "[G]"
  },
  {
    id: 51,
    seed: 7987,
    health: 33,
    tier: 3,
    type: "normal",
    act: 3,
    echo: "teom",
    deck: [
      "g-teom-teom-bilgini-152",
      "g-teom-goz-sovalyesi-126",
      "g-ruh-yanki-ritueli-293",
      "g-teom-manastir-yemini-138",
      "g-teom-beyaz-ritueli-148",
      "g-teom-kutsal-kesisi-151",
      "g-teom-teom-bilgini-152",
      "g-teom-manastir-vaizi-149",
      "g-teom-goz-fisiltisi-150",
      "g-ruh-akis-ritueli-311",
      "g-ruh-akis-feneri-305",
      "g-teom-goz-muhafizi-124",
      "g-teom-beyaz-demircisi-131",
      "g-konsey-sur-anlasmasi-67",
      "g-teom-goz-anlasmasi-123",
      "g-ruh-akis-feneri-305",
      "g-direnis-altin-isik-tasiyicisi-15",
      "g-ruh-akis-habercisi-285",
      "g-direnis-siginak-anlasmasi-21",
      "g-ruh-sisli-yemini-298"
    ],
    mutators: [
      {},
      {
        shield: 2
      }
    ],
    name: {
      tr: "III. Perde — Son Sur",
      en: "Son Sur"
    },
    opponent: "Teom Yargıcı",
    intro: {
      tr: "Mor damarlar taşların arasında atıyor. {opp} son direnişini kurdu.",
      en: "Violet veins pulse in the stone. {opp} has made its last stand."
    },
    reward: {
      shards: 20
    },
    src: "[G]"
  },
  {
    id: 52,
    seed: 8124,
    health: 34,
    tier: 3,
    type: "normal",
    act: 3,
    echo: "ash",
    deck: [
      "g-notr-toz-zebellahi-177",
      "g-karah-siyah-buyusu-100",
      "g-karah-mor-yavrusu-105",
      "g-notr-toz-koleksiyoncusu-183",
      "g-karah-katran-filizi-116",
      "g-karah-siyah-buyusu-100",
      "g-karah-carpik-emicisi-109",
      "g-karah-siyah-filizi-101",
      "g-notr-kul-cobani-173",
      "g-karah-obsidyen-kulu-107",
      "g-serseri-gri-pelerin-sokmasi-222",
      "g-notr-kul-buyusu-180",
      "g-karah-carpik-yavrusu-102",
      "g-karah-katran-kulu-108",
      "g-konsey-kale-buyusu-54",
      "g-notr-toz-zebellahi-177",
      "g-karah-katran-filizi-116",
      "g-karah-siyah-tasiyicisi-94",
      "g-karah-siyah-fisiltisi-82",
      "g-karah-siyah-yavrusu-88"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "III. Perde — Mor Damar Geçidi",
      en: "Mor Damar Geçidi"
    },
    opponent: "Yozlaşma Taşıyıcısı",
    intro: {
      tr: "Mor damarlar taşların arasında atıyor. {opp} son direnişini kurdu.",
      en: "Violet veins pulse in the stone. {opp} has made its last stand."
    },
    reward: {
      shards: 20
    },
    src: "[G]"
  },
  {
    id: 53,
    seed: 8261,
    health: 34,
    tier: 3,
    type: "elite",
    act: 3,
    echo: "white",
    deck: [
      "g-ruh-unutulmus-yemini-306",
      "g-ruh-akis-koru-masi-287",
      "g-ruh-bosluk-sesi-276",
      "g-ruh-sisli-yemini-298",
      "g-teom-kutsal-anlasmasi-125",
      "g-ruh-hatira-sesi-300",
      "g-ruh-unutulmus-yemini-306",
      "g-ruh-sisli-feneri-289",
      "g-ruh-bosluk-yemini-303",
      "g-ruh-akis-habercisi-285",
      "g-serseri-gri-pelerin-yemini-213",
      "g-ruh-akis-ritueli-311",
      "g-ruh-hatira-yuzu-283",
      "g-ruh-yanki-kalintisi-301",
      "g-ruh-akis-habercisi-285",
      "g-serseri-sis-kancalisi-221",
      "g-av-kanli-okcusu-255",
      "g-direnis-mantar-buyusu-31",
      "g-serseri-gri-pelerin-ritueli-232",
      "g-ruh-hatira-yuzu-283"
    ],
    mutators: [
      {},
      {
        kwAll: [
          "cabuk"
        ]
      }
    ],
    name: {
      tr: "III. Perde — Obsidyen Çukur",
      en: "Obsidyen Çukur"
    },
    opponent: "Boşluk Fenerleri",
    intro: {
      tr: "Hepsi tetikte — ilk onlar vuracak.",
      en: "All of them are poised — they will strike first."
    },
    reward: {
      shards: 34
    },
    src: "[G]"
  },
  {
    id: 54,
    seed: 8398,
    health: 34,
    tier: 3,
    type: "normal",
    act: 3,
    echo: "teom",
    deck: [
      "g-serseri-fisilti-ritueli-202",
      "golge-yolu",
      "g-serseri-gri-pelerin-sokmasi-222",
      "g-serseri-kor-hirsizi-212",
      "g-serseri-yankisiz-maskelisi-230",
      "g-serseri-yankisiz-hirsizi-197",
      "g-serseri-fisilti-kacagi-229",
      "g-serseri-fisilti-kacagi-229",
      "g-av-pence-ritueli-244",
      "g-serseri-yankisiz-yemini-203",
      "g-konsey-ferman-elcisi-56",
      "g-serseri-yankisiz-kacagi-209",
      "g-serseri-yankisiz-maskelisi-230",
      "g-serseri-gece-kancalisi-219",
      "g-konsey-kan-fisiltisi-63",
      "g-konsey-ferman-k-tibi-77",
      "g-serseri-yankisiz-ritueli-233",
      "g-konsey-kizil-buyusu-74",
      "g-serseri-gri-pelerin-yemini-213",
      "g-konsey-sur-zebellahi-72"
    ],
    mutators: [
      {},
      {
        shield: 2
      }
    ],
    name: {
      tr: "III. Perde — Yankı Vadisi",
      en: "Yankı Vadisi"
    },
    opponent: "Maskeli Olanlar",
    intro: {
      tr: "Mor damarlar taşların arasında atıyor. {opp} son direnişini kurdu.",
      en: "Violet veins pulse in the stone. {opp} has made its last stand."
    },
    reward: {
      shards: 20
    },
    src: "[G]"
  },
  {
    id: 55,
    seed: 8535,
    health: 35,
    tier: 3,
    type: "normal",
    act: 3,
    echo: "ash",
    deck: [
      "g-ruh-unutulmus-feneri-282",
      "g-teom-beyaz-muhafizi-142",
      "g-ruh-hatira-anlasmasi-291",
      "g-teom-goz-muhafizi-124",
      "g-teom-kutsal-kesisi-151",
      "g-teom-goz-vaizi-147",
      "g-av-pence-ritueli-244",
      "g-teom-goz-anlasmasi-123",
      "g-teom-goz-anlasmasi-123",
      "g-serseri-kor-kancalisi-211",
      "g-ruh-yanki-andici-310",
      "g-teom-serlunar-vaizi-130",
      "g-ruh-akis-koru-masi-287",
      "g-ruh-akis-habercisi-285",
      "g-teom-teom-ritueli-133",
      "g-teom-serlunar-kesisi-132",
      "g-teom-serlunar-vaizi-130",
      "g-teom-beyaz-demircisi-131",
      "g-teom-goz-buyusu-140",
      "g-teom-manastir-bilgini-122"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "III. Perde — Son Sur",
      en: "Son Sur"
    },
    opponent: "Beyaz Vaizler",
    intro: {
      tr: "Mor damarlar taşların arasında atıyor. {opp} son direnişini kurdu.",
      en: "Violet veins pulse in the stone. {opp} has made its last stand."
    },
    reward: {
      shards: 20
    },
    src: "[G]"
  },
  {
    id: 56,
    seed: 8672,
    health: 35,
    tier: 3,
    type: "tft",
    act: 3,
    echo: "white",
    deck: [
      "g-notr-kul-buyusu-180",
      "g-karah-carpik-tasiyicisi-111",
      "g-karah-siyah-anlasmasi-112",
      "g-karah-siyah-fisiltisi-82",
      "g-av-kanli-okcusu-255",
      "g-notr-toz-hurdacisi-176",
      "g-karah-obsidyen-tasiyicisi-89",
      "g-karah-katran-kulu-108",
      "g-notr-toz-fisiltisi-162",
      "g-karah-siyah-buyusu-100",
      "g-karah-obsidyen-buyusu-104",
      "g-karah-siyah-filizi-101",
      "g-karah-obsidyen-bedeli-115",
      "g-notr-kuzgunyuvasi-bedeli-192",
      "g-karah-katran-buyusu-79",
      "g-karah-mor-yavrusu-105",
      "g-karah-siyah-anlasmasi-112",
      "g-karah-siyah-buyusu-100",
      "g-karah-mor-surusu-98",
      "g-karah-katran-tasiyicisi-80"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "III. Perde — Mor Damar Geçidi",
      en: "Mor Damar Geçidi"
    },
    opponent: "Mor Sürü",
    intro: {
      tr: "Mor damarlar taşların arasında atıyor. {opp} son direnişini kurdu.",
      en: "Violet veins pulse in the stone. {opp} has made its last stand."
    },
    reward: {
      shards: 40
    },
    src: "[G]"
  },
  {
    id: 57,
    seed: 8809,
    health: 35,
    tier: 3,
    type: "normal",
    act: 3,
    echo: "teom",
    deck: [
      "g-teom-serlunar-vaizi-130",
      "g-direnis-kopru-kurucusu-6",
      "g-ruh-akis-ritueli-311",
      "g-teom-teom-bilgini-152",
      "g-ruh-bosluk-yuzu-284",
      "g-ruh-bosluk-feneri-288",
      "g-ruh-hatira-feneri-280",
      "g-ruh-unutulmus-andici-295",
      "g-ruh-akis-koru-masi-287",
      "g-teom-serlunar-ritueli-143",
      "g-teom-goz-muhafizi-124",
      "g-ruh-yanki-sesi-277",
      "g-teom-manastir-sovalyesi-120",
      "g-ruh-hatira-anlasmasi-291",
      "g-teom-manastir-bedeli-146",
      "g-ruh-unutulmus-yemini-306",
      "g-ruh-hatira-feneri-280",
      "g-teom-manastir-vaizi-149",
      "g-ruh-unutulmus-koru-masi-274",
      "g-teom-teom-bilgini-152"
    ],
    mutators: [
      {},
      {
        shield: 2
      }
    ],
    name: {
      tr: "III. Perde — Obsidyen Çukur",
      en: "Obsidyen Çukur"
    },
    opponent: "Akis Sürüsü",
    intro: {
      tr: "Mor damarlar taşların arasında atıyor. {opp} son direnişini kurdu.",
      en: "Violet veins pulse in the stone. {opp} has made its last stand."
    },
    reward: {
      shards: 20
    },
    src: "[G]"
  },
  {
    id: 58,
    seed: 8946,
    health: 36,
    tier: 3,
    type: "normal",
    act: 3,
    echo: "ash",
    deck: [
      "g-serseri-gece-buyusu-224",
      "g-serseri-fisilti-kacagi-229",
      "g-serseri-gri-pelerin-yemini-213",
      "g-konsey-kan-habercisi-62",
      "g-konsey-kan-k-tibi-75",
      "g-serseri-yankisiz-ritueli-233",
      "g-serseri-sis-pusucusu-218",
      "g-serseri-gece-kancalisi-219",
      "g-serseri-yankisiz-kacagi-209",
      "g-serseri-gri-pelerin-yemini-213",
      "g-serseri-fisilti-kacagi-229",
      "g-direnis-kopru-ritueli-24",
      "g-serseri-kor-kancalisi-211",
      "g-serseri-yankisiz-ritueli-233",
      "g-serseri-sis-bedeli-200",
      "g-konsey-kan-bedeli-50",
      "g-konsey-kan-muhafizi-44",
      "g-notr-toz-zebellahi-177",
      "g-serseri-sis-fisiltisi-227",
      "g-konsey-kan-muhbiri-71"
    ],
    mutators: [
      {},
      {}
    ],
    name: {
      tr: "III. Perde — Yankı Vadisi",
      en: "Yankı Vadisi"
    },
    opponent: "Sis Çetesi",
    intro: {
      tr: "Mor damarlar taşların arasında atıyor. {opp} son direnişini kurdu.",
      en: "Violet veins pulse in the stone. {opp} has made its last stand."
    },
    reward: {
      shards: 20
    },
    src: "[G]"
  },
  {
    id: 59,
    seed: 9083,
    health: 60,
    tier: 3,
    type: "boss",
    act: 3,
    echo: "teom",
    deck: [
      "g-karah-siyah-buyusu-100",
      "g-karah-obsidyen-kulu-107",
      "katran-emici",
      "g-karah-obsidyen-ritueli-92",
      "g-notr-kul-yemini-175",
      "g-karah-katran-yemini-85",
      "g-karah-siyah-anlasmasi-112",
      "g-ruh-akis-koru-masi-287",
      "g-konsey-sur-yemini-39",
      "g-teom-serlunar-demircisi-137",
      "g-notr-toz-bedeli-182",
      "g-karah-mor-yavrusu-105",
      "kizil-cizgi",
      "g-notr-tarlalar-gozcusu-171",
      "g-karah-siyah-kulu-86",
      "g-karah-mor-yemini-91",
      "g-notr-kul-buyusu-180",
      "g-karah-obsidyen-buyusu-104",
      "g-notr-toz-hancisi-189",
      "g-av-kurt-tazisi-266"
    ],
    mutators: [
      {},
      {
        hpBonus: 24,
        kwAll: [
          "ezici",
          "canavar"
        ],
        shield: 6,
        ozStart: 2
      }
    ],
    name: {
      tr: "Karah Kalbi",
      en: "The Karah Heart"
    },
    opponent: "Karah Kalbi",
    intro: {
      tr: "Yozlaşmanın attığı yer. Kalbi susturursan destan da susar.",
      en: "Where corruption beats. Silence the heart and the saga goes quiet too."
    },
    reward: {
      shards: 60
    },
    src: "[G]"
  }
];
